const APP_VERSION='2.4.4';
const BUILD_DATE='2026-07-13';
const ACTIVATION_CODE='271261';
const DB_NAME='agenda-policial-db';
const DEFAULT_STATE={activated:false,mode:null,view:'inicio',formations:[],tasks:[],notes:[],scheduleBlocks:[],schedulePhoto:null,schedulePhotoName:null,scheduleMeta:null,scheduleHistory:[],kardex:{fields:{},sourceText:''},settings:{lastBackup:null,lastUpdateCheck:null,lastCleanUpdate:null},drafts:{},archive:{formations:[],tasks:[],notes:[]}};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let state=structuredClone(DEFAULT_STATE), docs={}, deferredPrompt=null;

const store={db:null, async open(){return new Promise((res,rej)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=e=>e.target.result.createObjectStore('kv');req.onsuccess=e=>{this.db=e.target.result;res()};req.onerror=()=>rej(req.error)})}, async get(k){return new Promise(res=>{const tx=this.db.transaction('kv','readonly');const r=tx.objectStore('kv').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>res(null)})}, async set(k,v){return new Promise((res,rej)=>{const tx=this.db.transaction('kv','readwrite');tx.objectStore('kv').put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}};
async function save(){await store.set('state',state)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function todayISO(){return new Date().toISOString().slice(0,10)}
function timeNow(){return new Date().toTimeString().slice(0,5)}
function fmtDate(d){if(!d)return 'Sin fecha'; const x=new Date(d+'T00:00:00'); return x.toLocaleDateString('es-BO',{weekday:'short',day:'2-digit',month:'short'})}
function minutes(t){if(!t)return null; const m=String(t).match(/(\d{1,2})[:.](\d{2})/); return m?Number(m[1])*60+Number(m[2]):null}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function normalize(s=''){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/n[.º°]*\s*/g,'n').replace(/[-_]/g,' ').replace(/\s+/g,' ').trim()}
function contains(hay,q){const a=normalize(hay), b=normalize(q); if(!b)return true; const compact=a.replace(/\s+/g,''); return a.includes(b)||compact.includes(b.replace(/\s+/g,''))}
async function loadJSON(path){try{return await (await fetch(path)).json()}catch(e){console.warn('no load',path,e);return null}}
async function init(){await store.open(); const saved=await store.get('state'); if(saved) state={...structuredClone(DEFAULT_STATE),...saved,archive:{...DEFAULT_STATE.archive,...(saved.archive||{})},drafts:{...DEFAULT_STATE.drafts,...(saved.drafts||{})},settings:{...DEFAULT_STATE.settings,...(saved.settings||{})}}; if(localStorage.getItem('agenda-policial-activated')==='true') state.activated=true; bindSW(); render(); loadAllData().then(()=>{ ensureScheduleTemplate(); render(); }).catch(()=>{});} 
async function loadAllData(){docs.uniformes=await loadJSON('./data/reglamento-uniformes.json'); docs.sumario=await loadJSON('./data/reglamento-sumario-unipol.json'); docs.horario=await loadJSON('./data/horario-base.json'); docs.catalogo=await loadJSON('./data/biblioteca-catalogo.json'); await loadNorms();}
async function loadNorms(){const files=['cpe','ley-1178','ds-23215','ds-23318-a','ds-26237','ds-29820','ds-29536','codigo-penal','codigo-procedimiento-penal']; docs.norms=[]; for(const f of files){const d=await loadJSON(`./data/${f}.json`); if(d) docs.norms.push(d)}}
function scheduleBaseEntries(){const base=docs.horario||{}; return base.entradas||base.bloques||[]}
function normalizeScheduleEntry(e){return {...e,id:e.id||uid(),dia:normDayWord(e.dia)||normalize(e.dia||'lunes'),inicio:e.inicio||'',fin:e.fin||'',materia:e.materia||e.actividad||'',docente:e.docente||e.instructor||'',tipo:e.tipo||'clase',lugar:e.lugar||'',uniforme:e.uniforme||'',observacion:e.observacion||''}}
function isPlaceholderSchedule(){return !state.scheduleBlocks?.length || (state.scheduleBlocks.length<=2 && state.scheduleBlocks.every(b=>/horario por configurar/i.test(b.materia||b.actividad||'')))}
function seedSchedule(force=false){const entries=scheduleBaseEntries(); if(!entries.length)return; if(force||isPlaceholderSchedule()){state.scheduleBlocks=entries.map(normalizeScheduleEntry); state.scheduleMeta={...(docs.horario?.metadatos||{}),fuente_visual:docs.horario?.fuente_visual||'assets/horario-referencia.webp'}; if(!state.schedulePhotoName) state.schedulePhotoName='Horario de referencia institucional'; }}
function ensureScheduleTemplate(){seedSchedule(false); if(!state.scheduleMeta && docs.horario?.metadatos) state.scheduleMeta={...(docs.horario.metadatos||{}),fuente_visual:docs.horario?.fuente_visual||'assets/horario-referencia.webp'};}
async function restoreBaseSchedule(){if(!confirm('Esto reemplazará el horario actual por la estructura base precargada. El horario actual quedará en historial local. ¿Continuar?'))return; state.scheduleHistory=state.scheduleHistory||[]; if(state.scheduleBlocks?.length) state.scheduleHistory.push({id:uid(),date:new Date().toISOString(),blocks:state.scheduleBlocks,photo:state.schedulePhoto,name:state.schedulePhotoName}); seedSchedule(true); await save(); render(); toast('Estructura base restaurada')}
function bindSW(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e}); $('#updateNow')?.addEventListener('click',applyUpdate); if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>{window._swReg=reg; reg.update().catch(()=>{}); if(reg.waiting) showUpdateBanner(); reg.addEventListener('updatefound',()=>{const nw=reg.installing; if(!nw)return; nw.addEventListener('statechange',()=>{if(nw.state==='installed'&&navigator.serviceWorker.controller) showUpdateBanner()})}); navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!window._refreshing){window._refreshing=true; location.replace('./index.html?v='+APP_VERSION+'&r='+Date.now())}})}).catch(()=>{})}}
function appShell(content){return `<div class="app"><header class="top"><div class="top-row"><img src="./assets/escudo-policia.png" class="seal"><div class="title"><h1>Agenda Policial</h1><p>${state.mode==='profesional'?'Modo profesional':'Modo académico'} · v${APP_VERSION} <span class="version-dot">estable</span></p></div><div class="top-actions"><button class="icon-btn" onclick="openNotes()" title="Bloc de notas">▣</button><button class="icon-btn" onclick="openSettings()" title="Configuración">⚙</button></div></div><div class="search"><input id="globalSearch" placeholder="Buscar: 3A, faltas graves, tarea, formación..." onkeydown="if(event.key==='Enter') searchGlobal(this.value)"></div></header><main>${content}</main>${nav()}<button class="fab" onclick="openQuick()">+</button></div>`}
function nav(){const items=[['inicio','⌂','Inicio'],['formaciones','🛡','Formaciones'],['tareas','☑','Tareas'],['horario','▦','Horario'],['biblioteca','§','Biblioteca']];return `<nav class="bottom-nav">${items.map(i=>`<button class="nav-btn ${state.view===i[0]?'active':''}" onclick="go('${i[0]}')"><span>${i[1]}</span><span>${i[2]}</span></button>`).join('')}</nav>`}
async function go(v){state.view=v; await save(); render()}
function render(){if(!state.activated)return renderActivation(); if(!state.mode)return renderMode(); const map={inicio:renderInicio,formaciones:renderFormaciones,tareas:renderTareas,horario:renderHorario,biblioteca:renderBiblioteca}; $('#app').innerHTML=appShell((map[state.view]||renderInicio)()); wireView()}
function renderActivation(){ $('#app').innerHTML=`<div class="activation"><div class="activation-card"><img src="./assets/escudo-policia.png" class="seal"><h1>Agenda Policial</h1><p class="subtle">Ingrese el código de activación para usar la aplicación en este dispositivo.</p><div class="form"><input id="activationCode" type="password" inputmode="numeric" maxlength="6" autocomplete="off" placeholder="Código de activación" onkeydown="if(event.key==='Enter') activateApp()"><button class="btn" onclick="activateApp()">Activar</button></div><p class="subtle">El código se guarda localmente y solo vuelve a pedirse si se borran los datos o se reinstala.</p></div></div>`}
async function activateApp(){const v=$('#activationCode').value.trim(); if(v!==ACTIVATION_CODE)return toast('Código incorrecto'); state.activated=true; localStorage.setItem('agenda-policial-activated','true'); await save(); render()}
function renderMode(){ $('#app').innerHTML=`<div class="activation"><div class="activation-card"><h1>Elija modo inicial</h1><p class="subtle">Puede cambiarlo después en configuración.</p><div class="mode-grid"><button class="mode-card" onclick="setMode('academico')"><h3>🎓 Académico</h3><p>Horario de clases, tareas, formaciones y biblioteca.</p></button><button class="mode-card" onclick="setMode('profesional')"><h3>👮 Profesional</h3><p>Servicios, actividades, tareas y normativa.</p></button></div></div></div>`}
async function setMode(m){state.mode=m; await save(); render()}
function wireView(){ }
function currentDayKey(){return ['domingo','lunes','martes','miercoles','jueves','viernes','sabado'][new Date().getDay()]}
function getTodayBlocks(){const d=currentDayKey();return state.scheduleBlocks.filter(b=>normalize(b.dia)===d).sort((a,b)=>minutes(a.inicio)-minutes(b.inicio))}
function classifyBlock(b){const now=new Date(); const m=now.getHours()*60+now.getMinutes(), a=minutes(b.inicio), z=minutes(b.fin); if(a==null||z==null)return ''; if(m>=a&&m<z)return 'current'; if(m>=z)return 'finished'; if(m<a)return 'next'; return ''}
function nextEvent(list){const now=new Date(); const nowMin=now.getHours()*60+now.getMinutes(); return list.filter(e=>e.date===todayISO()&&minutes(e.time||e.formacion||e.inicio)>=nowMin).sort((a,b)=>minutes(a.time||a.formacion||a.inicio)-minutes(b.time||b.formacion||b.inicio))[0]||list.filter(e=>e.date>=todayISO()).sort((a,b)=>(a.date+(a.time||a.formacion||'99:99')).localeCompare(b.date+(b.time||b.formacion||'99:99')))[0]}
function countdown(date,time){if(!date||!time)return ''; const target=new Date(`${date}T${time}:00`); const diff=Math.round((target-new Date())/60000); if(diff<0)return 'En curso o finalizado'; if(diff<60)return `Faltan ${diff} min`; return `Faltan ${Math.floor(diff/60)} h ${diff%60} min`}
function renderInicio(){const blocks=getTodayBlocks(); const current=blocks.find(b=>classifyBlock(b)==='current'); const next=blocks.find(b=>classifyBlock(b)==='next'); const f=nextEvent(state.formations.filter(x=>x.status!=='archived')); const dueTasks=state.tasks.filter(t=>t.status!=='done'&&t.status!=='archived').sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999')).slice(0,4); return `<section><h2 class="section-title">Hoy</h2>${state.mode==='academico'&&current?classCard('En curso',current,'current'):state.mode==='academico'?`<div class="card dashboard-card"><h3>No hay clase en curso</h3><p>El horario académico se mostrará aquí cuando corresponda.</p></div>`:''}${state.mode==='academico'&&next?classCard('Siguiente clase',next,'next'):''}${f?formationCard(f,true):`<div class="card small"><h3>Sin formaciones o servicios próximos</h3><p>Cuando registre una formación o servicio aparecerá aquí.</p></div>`}<div class="row between"><h2 class="section-title">Tareas próximas</h2><button class="option-btn" onclick="go('tareas')">Ver todo</button></div>${dueTasks.length?dueTasks.map(taskCard).join(''):`<div class="card small"><p>No hay tareas académicas pendientes.</p></div>`}</section>`}
function classCard(title,b,kind){return `<div class="card dashboard-card ${kind==='next'?'priority':''} clickable" onclick="openClassDetail('${b.id}')"><span class="tag">${title}</span><h3>${esc(b.materia||b.actividad||'Actividad')}</h3><p><b>${b.inicio||''} - ${b.fin||''}</b> ${b.docente?' · '+esc(b.docente):''}</p>${b.lugar?`<p>📍 ${esc(b.lugar)}</p>`:''}${kind==='next'?`<p>${countdown(todayISO(),b.inicio)}</p>`:''}</div>`}
function formationCard(f,compact=false){return `<div class="card dashboard-card priority clickable" onclick="openFormation('${f.id}')"><div class="row between"><span class="tag warn">${esc(f.type||'Formación / servicio')}</span><button class="option-btn" onclick="event.stopPropagation();formationOptions('${f.id}')">⋮</button></div><h3>${esc(f.title||'Sin título')}</h3><p><b>${fmtDate(f.date)}</b>${f.arribo?` · Arribo ${esc(f.arribo)}`:''}${f.formacion?` · Formación ${esc(f.formacion)}`:''}</p>${f.place?`<p>📍 ${esc(f.place)}</p>`:''}${f.uniforme?`<p>👔 ${esc(f.uniforme)}</p>`:''}${compact&&f.formacion?`<p>${countdown(f.date,f.formacion)}</p>`:''}</div>`}
function taskCard(t){const overdue=t.dueDate&&t.dueDate<todayISO(); return `<div class="list-item ${overdue?'danger-card':''} clickable" onclick="openTask('${t.id}')"><div class="row"><button class="checkbox ${t.status==='done'?'on':''}" onclick="event.stopPropagation();toggleTask('${t.id}')">${t.status==='done'?'✓':''}</button><div style="flex:1"><h3>${esc(t.title||'Tarea')}</h3><p>${t.subject?esc(t.subject)+' · ':''}${t.dueDate?`Entrega: ${fmtDate(t.dueDate)}`:'Sin fecha'} ${t.dueTime?esc(t.dueTime):''}</p>${overdue?`<p class="status-red">Vencida</p>`:''}</div><button class="option-btn" onclick="event.stopPropagation();taskOptions('${t.id}')">⋮</button></div>${t.subtasks?.length?`<details><summary>Subtareas (${t.subtasks.filter(s=>s.done).length}/${t.subtasks.length})</summary><div class="list">${t.subtasks.map((s,i)=>`<div class="row"><button class="checkbox ${s.done?'on':''}" onclick="event.preventDefault();event.stopPropagation();toggleSubtask('${t.id}',${i})">${s.done?'✓':''}</button><span>${esc(s.text)}</span></div>`).join('')}</div></details>`:''}</div>`}
function renderFormaciones(){const active=state.formations.filter(f=>f.status!=='archived').sort((a,b)=>(a.date+(a.formacion||a.time||'')).localeCompare(b.date+(b.formacion||b.time||''))); return `<section><div class="row between"><h2 class="section-title">Formaciones y servicios</h2><button class="btn" onclick="openFormationForm()">Nueva</button></div><div class="card"><h3>Mensaje inteligente de formación</h3><p>Pegue aquí comunicados de formación, servicio, orden de guarnición o cambio de hora/lugar.</p><button class="btn secondary" onclick="openFormationSmart()">Pegar comunicado</button></div>${active.length?active.map(f=>formationCard(f)).join(''):`<div class="card small"><p>Sin formaciones o servicios registrados.</p></div>`}</section>`}
function renderTareas(){const active=state.tasks.filter(t=>t.status!=='archived'&&t.status!=='done'); const done=state.tasks.filter(t=>t.status==='done'); return `<section><div class="row between"><h2 class="section-title">Tareas académicas</h2><button class="btn" onclick="openTaskForm()">Nueva</button></div><div class="card"><h3>Mensaje inteligente de tarea</h3><p>Pegue instrucciones de trabajos, lecturas, entregas, exposiciones o requisitos académicos.</p><button class="btn secondary" onclick="openTaskSmart()">Pegar instrucción</button></div>${active.length?active.map(taskCard).join(''):`<div class="card small"><p>No hay tareas académicas pendientes.</p></div>`}<details class="card"><summary><b>Ver tareas cumplidas (${done.length})</b></summary><div class="list">${done.map(taskCard).join('')||'<p class="subtle">Sin tareas cumplidas.</p>'}</div></details></section>`}
function renderHorario(){const meta=state.scheduleMeta||docs.horario?.metadatos||{}; const rows=scheduleRows(); return `<section><div class=\"row between wrap\"><h2 class=\"section-title\">Horario académico</h2><button class=\"btn modern-action\" onclick=\"restoreBaseSchedule()\">Restaurar estructura base</button></div><div class=\"schedule-meta-card card\"><h3>${esc(meta.institucion||'ESP. Sub Sede Sucre')}</h3><p><b>${esc(meta.curso||'Curso de Capacitación Policial')}</b> ${meta.paralelo?` · Paralelo ${esc(meta.paralelo)}`:''}${meta.turno?` · Turno ${esc(meta.turno)}`:''}</p><p>${esc(meta.nivel||'Nivel')} ${meta.periodo?` · ${esc(meta.periodo)}`:''}</p><div class=\"row wrap schedule-toolbar\"><button class=\"btn secondary\" onclick=\"openScheduleImage()\">Ver imagen actual</button><button class=\"btn secondary\" onclick=\"openReferenceScheduleImage()\">Ver imagen de referencia</button><button class=\"btn secondary\" onclick=\"chooseScheduleFile()\">Subir imagen</button><button class=\"btn secondary\" onclick=\"takeSchedulePhoto()\">Tomar foto</button><button class=\"btn ghost\" onclick=\"openScheduleAnalyzer()\">Analizar imagen</button></div><input id=\"scheduleFile\" type=\"file\" accept=\"image/*\" class=\"hidden\"><input id=\"scheduleCamera\" type=\"file\" accept=\"image/*\" capture=\"environment\" class=\"hidden\"><p class=\"subtle\">La tabla ya está prearmada. Toque cualquier casillero para editar materia y docente/instructor.</p></div><div class=\"schedule-table-wrap card\"><div class=\"schedule-title-strip\"><b>Horario semanal editable</b><span>${state.scheduleBlocks.length} casilleros</span></div><table class=\"schedule-table\"><thead><tr><th>Horas</th>${scheduleDays().map(d=>`<th>${dayLabel(d)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>scheduleTableRow(r)).join('')}</tbody></table></div><div class=\"card small\"><h3>Regla obligatoria</h3><p>Cada casillero de clase debe conservar <b>materia/actividad</b> y <b>docente o instructor</b>. Si el OCR no lo detecta, el campo queda visible para completar antes de guardar.</p></div></section>`}
function scheduleDays(){return ['lunes','martes','miercoles','jueves','viernes']}
function dayLabel(d){return d==='miercoles'?'MIÉRCOLES':d.toUpperCase()}
function scheduleRows(){const order=['07:15-07:30','07:30-08:10','08:10-08:50','08:50-09:05','09:05-09:45','09:45-10:25','10:25-10:40','10:40-11:20','11:20-12:00','12:00-12:40','15:30-16:15','16:15-17:00','17:00-17:15','17:15-18:00']; const keys=new Set(order); (state.scheduleBlocks||[]).forEach(b=>{if(b.inicio&&b.fin)keys.add(`${b.inicio}-${b.fin}`)}); return [...keys].sort((a,b)=>minutes(a.split('-')[0])-minutes(b.split('-')[0])).map(k=>{const [inicio,fin]=k.split('-'); return {inicio,fin}})}
function findScheduleCell(day,inicio,fin){return (state.scheduleBlocks||[]).find(b=>normalize(b.dia)===day&&b.inicio===inicio&&b.fin===fin)}
function scheduleTableRow(r){const cells=scheduleDays().map(day=>{const b=findScheduleCell(day,r.inicio,r.fin); const isBreak=b&&/descanso/i.test(b.materia||''); const isSpecial=b&&/(parte|hora mística|hora mistica)/i.test(b.materia||''); const cls=isBreak?'break':isSpecial?'special':b?'filled':'empty'; return `<td class=\"schedule-cell ${cls}\" onclick=\"openScheduleCell('${day}','${r.inicio}','${r.fin}')\">${b?`<div class=\"cell-subject\">${esc(b.materia||'')}</div><div class=\"cell-teacher\">${esc(b.docente||b.instructor||'Docente / instructor pendiente')}</div>`:`<div class=\"cell-empty\">Toque para llenar</div><div class=\"cell-teacher\">Docente / instructor</div>`}</td>`}).join(''); return `<tr><th class=\"time-col\">${esc(r.inicio)}<br><span>${esc(r.fin)}</span></th>${cells}</tr>`}
function openScheduleCell(day,inicio,fin){let b=findScheduleCell(day,inicio,fin); if(!b){b={id:uid(),dia:day,inicio,fin,materia:'',docente:'',tipo:'clase',lugar:'',uniforme:'',observacion:''}; state.scheduleBlocks.push(b)} openScheduleBlockForm(b.id)}
async function selectDay(d){state.selectedDay=d; await save(); render()}
function renderBiblioteca(){const catalog=docs.catalogo?.documentos||[]; return `<section><h2 class="section-title">Biblioteca normativa</h2><div class="card library-search-card"><div class="row wrap"><input id="libQuery" class="grow" placeholder="Buscar: 3A, 3B, uniforme 4, faltas graves..." onkeydown="if(event.key==='Enter') doLibrarySearch(this.value)"><button class="btn" onclick="doLibrarySearch($('#libQuery').value)">Buscar</button></div><p class="subtle">La búsqueda prioriza uniformes por código exacto y mantiene acceso al PDF original.</p><div class="row wrap"><button class="btn secondary" onclick="showUniformIndex()">Índice de uniformes</button><a class="btn secondary link-btn" href="./assets/reglamento-uniformes-2021.pdf" target="_blank" rel="noopener">Ver PDF original</a><button class="btn ghost" onclick="auditUniformImages()">Auditar imágenes</button></div></div><div id="libResults"></div><h3 class="section-title">Documentos</h3>${catalog.map(d=>`<div class="list-item clickable doc-item" onclick="openDoc('${d.id||d.slug||d.codigo||d.nombre}')"><h3>${esc(d.titulo||d.nombre)}</h3><p>${esc(d.descripcion||'Documento normativo disponible para consulta.')}</p></div>`).join('')}<div class="card"><h3>Accesos rápidos</h3><div class="row wrap"><button class="btn secondary" onclick="quickSumario('Faltas Leves')">Faltas leves</button><button class="btn secondary" onclick="quickSumario('Faltas Graves')">Faltas graves</button><button class="btn secondary" onclick="quickSumario('Faltas Gravísimas')">Faltas gravísimas</button><button class="btn secondary" onclick="doLibrarySearch('Uniforme N° 3-B Tropical')">3B Tropical</button></div></div></section>`}
function renderNotes(){const notes=state.notes.filter(n=>!n.archived); return `<section><div class="row between"><h2 class="section-title">Bloc de notas</h2><button class="btn" onclick="openNoteForm()">+</button></div><div class="tabs"><button class="active">Todo</button><button onclick="showArchivedNotes()">Archivadas</button></div><div class="note-grid">${notes.map(n=>`<div class="note-card clickable" onclick="openNoteForm('${n.id}')"><h3>${esc(n.title||'Sin título')}</h3><p>${esc((n.text||'').slice(0,130))}${(n.text||'').length>130?'...':''}</p><div class="muted">${new Date(n.updated||n.created).toLocaleString('es-BO')}</div></div>`).join('')||'<div class="card small"><p>No hay notas guardadas.</p></div>'}</div></section>`}
function showModal(html){$('#modalRoot').innerHTML=`<div class="modal-bg" onclick="if(event.target.className==='modal-bg') closeModal()"><div class="modal">${html}</div></div>`}
function closeModal(){ $('#modalRoot').innerHTML='' }
function openQuick(){showModal(`<h2>Agregar</h2><div class="drawer-list"><button class="drawer-btn" onclick="closeModal();openFormationForm()">🛡 Formación / servicio</button><button class="drawer-btn" onclick="closeModal();openTaskForm()">☑ Tarea académica</button><button class="drawer-btn" onclick="closeModal();openNoteForm()">▣ Bloc de notas</button><button class="drawer-btn" onclick="closeModal();go('horario');setTimeout(chooseScheduleFile,150)">▦ Foto de horario</button></div>`)}
function openNotes(){ $('#app').innerHTML=appShell(renderNotes()) }
function openSettings(){showModal(`<button class="icon-btn close" onclick="closeModal()">×</button><div class="settings-head"><img src="./assets/escudo-policia.png" class="seal small-seal"><div><h2>Configuración</h2><p>Agenda Policial · v${APP_VERSION} · compilación ${BUILD_DATE}</p></div></div><div class="status-grid"><div><b>Modo</b><span>${state.mode}</span></div><div><b>Instalación</b><span>${installMode()}</span></div><div><b>Activación</b><span>${state.activated?'activa':'no activa'}</span></div><div><b>Conexión</b><span>${navigator.onLine?'en línea':'sin conexión'}</span></div></div><div class="drawer-list settings-list"><button class="drawer-btn" onclick="toggleMode()">Cambiar modo actual: ${state.mode}</button><button class="drawer-btn" onclick="openKardex()">Ficha Kardex / datos personales</button><button class="drawer-btn" onclick="exportBackup()">Exportar respaldo JSON</button><button class="drawer-btn" onclick="importBackup()">Importar respaldo JSON</button><button class="drawer-btn important" onclick="checkUpdate()">Buscar actualización desde GitHub</button><button class="drawer-btn important" onclick="forceCleanUpdate()">Forzar actualización limpia</button><button class="drawer-btn" onclick="cleanAppCaches()">Limpiar caché sin borrar mis datos</button><button class="drawer-btn" onclick="openDiagnostics()">Estado técnico / diagnóstico</button><button class="drawer-btn" onclick="location.href='./reset.html'">Reparar actualización bloqueada</button><button class="drawer-btn" onclick="auditUniformImages()">Auditar imágenes de uniformes</button><button class="drawer-btn" onclick="toast('Último respaldo: ${state.settings.lastBackup||'sin respaldo'}')">Último respaldo</button></div><p class="subtle">Estas acciones limpian caché y Service Worker, pero no borran IndexedDB ni sus registros locales.</p><input id="backupImport" type="file" accept="application/json" class="hidden">`)}
async function toggleMode(){state.mode=state.mode==='academico'?'profesional':'academico'; await save(); closeModal(); render()}
function buildForm(fields, obj={}){return `<div class="form">${fields.map(f=>{const v=obj[f.name]??''; const label=`<label>${f.label}</label>`; if(f.type==='textarea')return `${label}<textarea name="${f.name}">${esc(v)}</textarea>`; if(f.type==='select')return `${label}<select name="${f.name}">${f.options.map(o=>`<option ${v===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`; return `${label}<input name="${f.name}" type="${f.type||'text'}" value="${esc(v)}" ${f.placeholder?`placeholder="${esc(f.placeholder)}"`:''}>`}).join('')}</div>`}
function formData(root){return Object.fromEntries(new FormData(root).entries())}
function openFormationForm(id=null, pre={}){const f=id?state.formations.find(x=>x.id===id):{date:todayISO(),...pre}; const fields=[{name:'type',label:'Tipo de actividad',type:'select',options:['Formación','Servicio extraordinario','Orden de guarnición','Acto institucional','Control','Otro']},{name:'title',label:'Título / nombre'},{name:'date',label:'Fecha',type:'date'},{name:'arribo',label:'Hora de arribo',type:'time'},{name:'formacion',label:'Hora de formación',type:'time'},{name:'parte',label:'Hora de parte',type:'time'},{name:'place',label:'Lugar'},{name:'location',label:'Link de ubicación'},{name:'uniforme',label:'Uniforme'},{name:'observations',label:'Observaciones',type:'textarea'},{name:'original',label:'Mensaje original',type:'textarea'}]; showModal(`<h2>${id?'Editar':'Nueva'} formación / servicio</h2><form id="formationForm">${buildForm(fields,f)}<div class="form-actions"><button class="btn" type="submit">Guardar</button><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button></div></form>`); $('#formationForm').onsubmit=async e=>{e.preventDefault(); const data=formData(e.target); if(id)Object.assign(f,data,{updated:new Date().toISOString()}); else state.formations.push({...data,id:uid(),status:'active',created:new Date().toISOString()}); await save(); closeModal(); render(); toast('Formación guardada') }}
function openFormationSmart(){showModal(`<h2>Mensaje inteligente de formación</h2><p class="subtle">Pega el comunicado recibido. La app conserva el mensaje original y propone datos editables.</p><textarea id="smartText" placeholder="Pegar comunicado..." style="width:100%;min-height:220px"></textarea><div class="form-actions"><button class="btn" onclick="analyzeFormation()">Analizar</button><button class="btn secondary" onclick="closeModal()">Cancelar</button></div>`)}
function analyzeFormation(){const raw=$('#smartText').value.trim(); if(!raw)return toast('Pegue un mensaje'); const a=parseFormation(raw); const titles=suggestTitles(raw,'formation'); showModal(`<h2>Revisar formación</h2><p>Elige un título:</p><div class="row wrap">${titles.map(t=>`<button class="option-btn" onclick="$('#fTitle').value='${esc(t)}'">${esc(t)}</button>`).join('')}</div><form id="formationForm">${buildForm([{name:'title',label:'Título'},{name:'type',label:'Tipo',type:'select',options:['Formación','Servicio extraordinario','Orden de guarnición','Acto institucional','Control','Otro']},{name:'date',label:'Fecha',type:'date'},{name:'arribo',label:'Hora de arribo',type:'time'},{name:'formacion',label:'Hora de formación',type:'time'},{name:'parte',label:'Hora de parte',type:'time'},{name:'place',label:'Lugar'},{name:'location',label:'Link de ubicación'},{name:'uniforme',label:'Uniforme'},{name:'observations',label:'Observaciones',type:'textarea'},{name:'original',label:'Mensaje original',type:'textarea'}],{...a,title:titles[0],original:raw})}<div class="form-actions"><button class="btn" type="submit">Guardar</button><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button></div></form>`); $('input[name="title"]').id='fTitle'; $('#formationForm').onsubmit=async e=>{e.preventDefault(); state.formations.push({...formData(e.target),id:uid(),status:'active',created:new Date().toISOString()}); await save(); closeModal(); render(); toast('Formación guardada')}}
function parseFormation(raw){const t=raw; const h=[...t.matchAll(/(?:hora(?:\s+de)?\s*(formaci[oó]n|arribo|parte)?|arribo|formaci[oó]n|parte)\D{0,25}(\d{1,2})[:.](\d{2})/gi)]; const out={date:extractDate(t),observations:t}; h.forEach(m=>{const label=normalize(m[1]||m[0]); const val=m[2].padStart(2,'0')+':'+m[3]; if(label.includes('arribo'))out.arribo=val; else if(label.includes('parte'))out.parte=val; else out.formacion=val}); const lugar=t.match(/(?:lugar|concentraci[oó]n|ubicaci[oó]n)\s*[:\-]?\s*([^\n]+)/i); if(lugar)out.place=lugar[1].trim(); const link=t.match(/https?:\/\/\S+/i); if(link)out.location=link[0]; const uni=t.match(/(?:uniforme|prendas base|uniforme de aulas|control de uniforme)\s*[:\-]?\s*([^\n]+)/i); if(uni)out.uniforme=uni[1].trim(); if(/servicio|orden de guarnici[oó]n|acto|desfile/i.test(t))out.type='Servicio extraordinario'; return out}
function extractDate(t){const iso=t.match(/(20\d{2})[-\/](\d{1,2})[-\/](\d{1,2})/); if(iso)return `${iso[1]}-${iso[2].padStart(2,'0')}-${iso[3].padStart(2,'0')}`; const dm=t.match(/(\d{1,2})\s+de\s+([a-záéíóú]+)\s+de\s+(20\d{2})/i); const months={enero:1,febrero:2,marzo:3,abril:4,mayo:5,junio:6,julio:7,agosto:8,septiembre:9,setiembre:9,octubre:10,noviembre:11,diciembre:12}; if(dm){const mm=months[normalize(dm[2])]; if(mm)return `${dm[3]}-${String(mm).padStart(2,'0')}-${dm[1].padStart(2,'0')}`} return todayISO()}
function suggestTitles(raw,type){const n=normalize(raw); if(type==='task'){if(n.includes('expos'))return ['Preparar exposición','Exposición pendiente','Trabajo de exposición']; if(n.includes('leer'))return ['Lectura asignada','Leer material de clase','Lectura pendiente']; if(n.includes('present'))return ['Presentar trabajo','Entrega académica','Presentación pendiente']; return ['Tarea académica pendiente','Trabajo de clase','Actividad académica']} if(n.includes('rectificando')||n.includes('nueva hora'))return ['Rectificación de formación','Cambio de hora','Actualización de servicio']; if(n.includes('orden de guarnicion'))return ['Orden de guarnición','Servicio por orden de guarnición','Actividad institucional']; if(n.includes('formacion'))return ['Formación general','Nueva formación','Control de formación']; if(n.includes('servicio'))return ['Servicio extraordinario','Servicio programado','Actividad de servicio']; return ['Comunicado de formación','Actividad institucional','Instrucción recibida']}
function openFormation(id){const f=state.formations.find(x=>x.id===id); if(!f)return; showModal(`<button class="icon-btn close" onclick="closeModal()">×</button><h2>${esc(f.title)}</h2><p><span class="tag warn">${esc(f.type||'Formación')}</span></p><p><b>Fecha:</b> ${fmtDate(f.date)}</p><p><b>Arribo:</b> ${esc(f.arribo||'')} · <b>Formación:</b> ${esc(f.formacion||'')} · <b>Parte:</b> ${esc(f.parte||'')}</p><p><b>Lugar:</b> ${esc(f.place||'')}</p><p><b>Uniforme:</b> ${esc(f.uniforme||'')}</p>${f.location?`<p><a href="${esc(f.location)}" target="_blank">Abrir ubicación</a></p>`:''}<h3>Observaciones</h3><p>${esc(f.observations||'')}</p><h3>Mensaje original</h3><pre class="article-text">${esc(f.original||'')}</pre><div class="row wrap"><button class="btn" onclick="closeModal();openFormationForm('${f.id}')">Editar</button><button class="btn secondary" onclick="archiveFormation('${f.id}')">Archivar</button><button class="btn danger" onclick="deleteFormation('${f.id}')">Eliminar</button></div>`)}
async function archiveFormation(id){const f=state.formations.find(x=>x.id===id); if(f)f.status='archived'; await save(); closeModal(); render(); toast('Archivado')}
async function deleteFormation(id){if(!confirm('¿Eliminar formación?'))return; state.formations=state.formations.filter(x=>x.id!==id); await save(); closeModal(); render(); toast('Eliminado')}
function formationOptions(id){showModal(`<h2>Opciones</h2><div class="drawer-list"><button class="drawer-btn" onclick="closeModal();openFormation('${id}')">Ver detalle</button><button class="drawer-btn" onclick="closeModal();openFormationForm('${id}')">Editar</button><button class="drawer-btn" onclick="duplicateFormation('${id}')">Duplicar</button><button class="drawer-btn" onclick="archiveFormation('${id}')">Archivar</button><button class="drawer-btn" onclick="deleteFormation('${id}')">Eliminar</button></div>`)}
async function duplicateFormation(id){const f=state.formations.find(x=>x.id===id); if(f){state.formations.push({...f,id:uid(),title:f.title+' (copia)',created:new Date().toISOString()}); await save(); closeModal(); render()}}
function openTaskForm(id=null, pre={}){const t=id?state.tasks.find(x=>x.id===id):{dueDate:todayISO(),subtasks:[],...pre}; showModal(`<h2>${id?'Editar':'Nueva'} tarea académica</h2><form id="taskForm">${buildForm([{name:'subject',label:'Materia'},{name:'title',label:'Título de la tarea'},{name:'dueDate',label:'Fecha de entrega',type:'date'},{name:'dueTime',label:'Hora de entrega',type:'time'},{name:'kind',label:'Tipo',type:'select',options:['Personal','Grupo','Lectura','Exposición','Documento','Otro']},{name:'description',label:'Descripción',type:'textarea'},{name:'subtasksText',label:'Subtareas, una por línea',type:'textarea'},{name:'original',label:'Mensaje original',type:'textarea'}],{...t,subtasksText:(t.subtasks||[]).map(s=>s.text).join('\n')})}<div class="form-actions"><button class="btn" type="submit">Guardar</button><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button></div></form>`); $('#taskForm').onsubmit=async e=>{e.preventDefault(); const data=formData(e.target); data.subtasks=(data.subtasksText||'').split('\n').map(x=>x.trim()).filter(Boolean).map((text,i)=>({text,done:(t.subtasks||[])[i]?.done||false})); delete data.subtasksText; if(id)Object.assign(t,data,{updated:new Date().toISOString()}); else state.tasks.push({...data,id:uid(),status:'pending',created:new Date().toISOString()}); await save(); closeModal(); render(); toast('Tarea guardada') }}
function openTaskSmart(){showModal(`<h2>Mensaje inteligente de tarea académica</h2><textarea id="smartText" placeholder="Pegar instrucción de tarea..." style="width:100%;min-height:220px"></textarea><div class="form-actions"><button class="btn" onclick="analyzeTask()">Analizar</button><button class="btn secondary" onclick="closeModal()">Cancelar</button></div>`)}
function analyzeTask(){const raw=$('#smartText').value.trim(); if(!raw)return toast('Pegue un mensaje'); const titles=suggestTitles(raw,'task'); const a=parseTask(raw); showModal(`<h2>Revisar tarea</h2><p>Elige un título:</p><div class="row wrap">${titles.map(t=>`<button class="option-btn" onclick="$('input[name=title]').value='${esc(t)}'">${esc(t)}</button>`).join('')}</div><form id="taskForm">${buildForm([{name:'subject',label:'Materia'},{name:'title',label:'Título de la tarea'},{name:'dueDate',label:'Fecha de entrega',type:'date'},{name:'dueTime',label:'Hora de entrega',type:'time'},{name:'kind',label:'Tipo',type:'select',options:['Personal','Grupo','Lectura','Exposición','Documento','Otro']},{name:'description',label:'Descripción',type:'textarea'},{name:'subtasksText',label:'Subtareas, una por línea',type:'textarea'},{name:'original',label:'Mensaje original',type:'textarea'}],{...a,title:titles[0],description:raw,original:raw})}<div class="form-actions"><button class="btn" type="submit">Guardar</button><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button></div></form>`); $('#taskForm').onsubmit=async e=>{e.preventDefault(); const data=formData(e.target); data.subtasks=(data.subtasksText||'').split('\n').map(x=>x.trim()).filter(Boolean).map(text=>({text,done:false})); delete data.subtasksText; state.tasks.push({...data,id:uid(),status:'pending',created:new Date().toISOString()}); await save(); closeModal(); render(); toast('Tarea guardada')}}
function parseTask(raw){const out={dueDate:extractDate(raw)}; const mat=raw.match(/(?:materia|asignatura)\s*[:\-]?\s*([^\n]+)/i); if(mat)out.subject=mat[1].trim(); const hh=raw.match(/(\d{1,2})[:.](\d{2})/); if(hh)out.dueTime=hh[1].padStart(2,'0')+':'+hh[2]; if(/grupo|grupal/i.test(raw))out.kind='Grupo'; else if(/leer|lectura/i.test(raw))out.kind='Lectura'; else if(/expos/i.test(raw))out.kind='Exposición'; return out}
function openTask(id){const t=state.tasks.find(x=>x.id===id); if(!t)return; showModal(`<button class="icon-btn close" onclick="closeModal()">×</button><h2>${esc(t.title)}</h2><p><b>Materia:</b> ${esc(t.subject||'')}</p><p><b>Entrega:</b> ${fmtDate(t.dueDate)} ${esc(t.dueTime||'')}</p><p><b>Tipo:</b> ${esc(t.kind||'')}</p><h3>Descripción</h3><p>${esc(t.description||'')}</p>${t.subtasks?.length?`<h3>Subtareas</h3>${t.subtasks.map((s,i)=>`<div class="row"><button class="checkbox ${s.done?'on':''}" onclick="toggleSubtask('${t.id}',${i})">${s.done?'✓':''}</button><span>${esc(s.text)}</span></div>`).join('')}`:''}<h3>Mensaje original</h3><pre class="article-text">${esc(t.original||'')}</pre><div class="row wrap"><button class="btn" onclick="closeModal();openTaskForm('${t.id}')">Editar</button><button class="btn secondary" onclick="toggleTask('${t.id}')">${t.status==='done'?'Marcar pendiente':'Marcar cumplida'}</button><button class="btn danger" onclick="deleteTask('${t.id}')">Eliminar</button></div>`)}
async function toggleTask(id){const t=state.tasks.find(x=>x.id===id); if(!t)return; t.status=t.status==='done'?'pending':'done'; t.updated=new Date().toISOString(); await save(); closeModal(); render(); toast(t.status==='done'?'Tarea cumplida':'Tarea pendiente')}
async function toggleSubtask(id,i){const t=state.tasks.find(x=>x.id===id); if(!t||!t.subtasks[i])return; t.subtasks[i].done=!t.subtasks[i].done; await save(); render();}
function taskOptions(id){showModal(`<h2>Opciones</h2><div class="drawer-list"><button class="drawer-btn" onclick="closeModal();openTask('${id}')">Ver detalle</button><button class="drawer-btn" onclick="closeModal();openTaskForm('${id}')">Editar</button><button class="drawer-btn" onclick="toggleTask('${id}')">Cumplida / pendiente</button><button class="drawer-btn" onclick="archiveTask('${id}')">Archivar</button><button class="drawer-btn" onclick="deleteTask('${id}')">Eliminar</button></div>`)}
async function archiveTask(id){const t=state.tasks.find(x=>x.id===id); if(t)t.status='archived'; await save(); closeModal(); render()}
async function deleteTask(id){if(!confirm('¿Eliminar tarea?'))return; state.tasks=state.tasks.filter(x=>x.id!==id); await save(); closeModal(); render()}
function openNoteForm(id=null){const n=id?state.notes.find(x=>x.id===id):{title:'',text:'',category:''}; showModal(`<button class="icon-btn close" onclick="closeModal()">×</button><h2>${id?'Editar':'Nueva'} nota</h2><p class="subtle">Bloc de notas policial. Escriba libremente; se puede editar después.</p><form id="noteForm" class="note-editor-form">${buildForm([{name:'title',label:'Título'},{name:'category',label:'Carpeta / categoría'},{name:'text',label:'Texto',type:'textarea'}],n)}<div class="form-actions note-actions"><button class="btn" type="submit">Guardar</button><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button></div></form>`); const textArea=$('#noteForm textarea[name="text"]'); if(textArea) textArea.classList.add('note-textarea'); $('#noteForm').onsubmit=async e=>{e.preventDefault(); const data=formData(e.target); if(id)Object.assign(n,data,{updated:new Date().toISOString()}); else state.notes.push({...data,id:uid(),created:new Date().toISOString(),updated:new Date().toISOString(),archived:false}); await save(); closeModal(); openNotes(); toast('Nota guardada')}}
function openScheduleImage(){if(!state.schedulePhoto)return toast('No hay imagen propia cargada. Puede ver la imagen de referencia.'); showModal(`<h2>Imagen actual del horario</h2><img class=\"image-preview\" src=\"${state.schedulePhoto}\"><div class=\"row wrap\"><button class=\"btn secondary\" onclick=\"chooseScheduleFile()\">Reemplazar desde archivos</button><button class=\"btn secondary\" onclick=\"takeSchedulePhoto()\">Tomar foto</button><button class=\"btn danger\" onclick=\"removeScheduleImage()\">Eliminar imagen</button></div>`)}
function openReferenceScheduleImage(){const src=(state.scheduleMeta?.fuente_visual||docs.horario?.fuente_visual||'assets/horario-referencia.webp'); showModal(`<h2>Imagen de referencia del horario</h2><img class=\"image-preview schedule-reference-image\" src=\"./${esc(src)}\"><p class=\"subtle\">Esta imagen queda como referencia visual. La tabla editable ya está armada con sus campos.</p><div class=\"row wrap\"><button class=\"btn\" onclick=\"restoreBaseSchedule()\">Restaurar tabla base</button><button class=\"btn secondary\" onclick=\"closeModal()\">Cerrar</button></div>`)}
function chooseScheduleFile(){closeModal(); $('#scheduleFile')?.click(); setTimeout(()=>{const input=$('#scheduleFile'); if(input) input.onchange=e=>loadScheduleImage(e.target.files[0])},50)}
function takeSchedulePhoto(){closeModal(); $('#scheduleCamera')?.click(); setTimeout(()=>{const input=$('#scheduleCamera'); if(input) input.onchange=e=>loadScheduleImage(e.target.files[0])},50)}
function loadScheduleImage(file){if(!file)return; const rd=new FileReader(); rd.onload=async()=>{state.schedulePhoto=rd.result; state.schedulePhotoName=file.name; await save(); render(); toast('Imagen cargada')}; rd.readAsDataURL(file)}
async function removeScheduleImage(){state.schedulePhoto=null; state.schedulePhotoName=null; await save(); closeModal(); render()}
function openScheduleAnalyzer(){showModal(`<h2>Analizar horario</h2>${state.schedulePhoto?`<img class="image-preview" src="${state.schedulePhoto}">`:'<p>No hay imagen cargada.</p>'}<p class="subtle">Suba una imagen de horario desde WhatsApp/galería o tome una foto. La app intentará leerla y convertirla en bloques editables. Si el OCR no logra leer bien, pegue o corrija el texto aquí.</p><div class="row wrap"><button class="btn secondary" onclick="chooseScheduleFile()">Subir otra imagen</button><button class="btn secondary" onclick="takeSchedulePhoto()">Tomar foto</button>${state.schedulePhoto?'<button class="btn" onclick="runScheduleOCR()">Leer imagen automáticamente</button>':''}</div><div id="ocrStatus" class="subtle"></div><textarea id="scheduleText" style="width:100%;min-height:200px" placeholder="También puede pegar texto reconocido. Ej.: 07:30-08:10 Planificación Estratégica   Inteligencia Estratégica   Procedimientos Especiales..."></textarea><div class="form-actions"><button class="btn" onclick="parseScheduleText()">Crear bloques</button><button class="btn secondary" onclick="closeModal()">Cancelar</button></div>`)}
async function runScheduleOCR(){if(!state.schedulePhoto)return toast('Primero suba una imagen'); const st=$('#ocrStatus'); st.textContent='Preparando lectura OCR...'; try{let text=''; if(window.Tesseract){const result=await Tesseract.recognize(state.schedulePhoto,'spa',{logger:m=>{if(m.status) st.textContent=`OCR: ${m.status} ${m.progress?Math.round(m.progress*100)+'%':''}`}}); text=result?.data?.text||'';} else if('TextDetector' in window){const img=new Image(); img.src=state.schedulePhoto; await img.decode(); const detector=new TextDetector(); const found=await detector.detect(img); text=found.map(x=>x.rawValue).join('\n');} else {st.textContent='Este navegador no tiene OCR disponible. Puede pegar el texto o usar el análisis manual.'; return toast('OCR no disponible en este dispositivo');} $('#scheduleText').value=text.trim(); st.textContent=text.trim()?'Texto detectado. Revise y pulse Crear bloques.':'No se pudo leer texto. Pruebe con una imagen más nítida o pegue el texto.'; if(text.trim()) parseScheduleText(false); }catch(e){console.error(e); st.textContent='No se pudo analizar la imagen. Puede pegar el texto o registrar manualmente.'; toast('Falló la lectura OCR')}}
function cleanOCRLine(line){return String(line||'').replace(/[|]/g,'  ').replace(/[–—]/g,'-').replace(/(\d{1,2})[.;](\d{2})/g,'$1:$2').replace(/\s+/g,' ').trim()}
function normDayWord(w=''){const n=normalize(w); if(n.startsWith('lun'))return 'lunes'; if(n.startsWith('mar'))return 'martes'; if(n.startsWith('mie'))return 'miercoles'; if(n.startsWith('jue'))return 'jueves'; if(n.startsWith('vie'))return 'viernes'; if(n.startsWith('sab'))return 'sabado'; if(n.startsWith('dom'))return 'domingo'; return ''}
function splitCells(rest){let s=String(rest||'').trim(); if(!s)return []; let parts=s.split(/\s{2,}|\t|¦|\u2502|\u2758/g).map(x=>x.trim()).filter(Boolean); if(parts.length<=1){parts=s.split(/(?=\b(?:PLANIFICACION|INTELIGENCIA|PROCEDIMIENTOS|CIENCIA|ADMINISTRACION|AUDITORIA|METODOS|TRABAJO|ACONDICIONAMIENTO|TECNICAS|DESCANSO|PARTE)\b)/i).map(x=>x.trim()).filter(Boolean);} return parts}
function splitSubjectTeacher(txt){let s=String(txt||'').replace(/\s+/g,' ').trim(); const m=s.match(/^(.*?)(\b(?:Lic\.|My\.|Mayor|My|Cnl\.|Coronel|Tcnl\.|Cap\.|Sgto\.|Sof\.|Ing\.|Dr\.|Dra\.|Instructor(?:a)?|Docente).*)$/i); if(m)return {materia:m[1].trim(),docente:m[2].trim()}; return {materia:s,docente:''}}
function parseScheduleText(showEmpty=true){const text=$('#scheduleText')?.value||''; const rows=[]; const days=['lunes','martes','miercoles','jueves','viernes']; const lines=text.split(/\n+/).map(cleanOCRLine).filter(Boolean); for(const line of lines){let m=line.match(/\b(lunes|martes|mi[eé]rcoles|miercoles|jueves|viernes|s[aá]bado|domingo)\b.*?(\d{1,2}:\d{2})\s*[-a]\s*(\d{1,2}:\d{2})\s+(.+)/i); if(m){const st=splitSubjectTeacher(m[4]); rows.push({dia:normDayWord(m[1]),inicio:m[2],fin:m[3],materia:st.materia,docente:st.docente,lugar:'',observacion:''}); continue;} m=line.match(/^(\d{1,2}:\d{2})\s*[-a]\s*(\d{1,2}:\d{2})\s+(.+)/i); if(m){const ini=m[1], fin=m[2], rest=m[3]; const cells=splitCells(rest).filter(c=>!/^horas?$/i.test(c)); if(cells.length>=2){cells.slice(0,5).forEach((cell,i)=>{if(!cell||/^[-_]+$/.test(cell))return; const st=splitSubjectTeacher(cell); rows.push({dia:days[i]||'lunes',inicio:ini,fin:fin,materia:st.materia,docente:st.docente,lugar:'',observacion:''})});} else if(cells.length===1){const st=splitSubjectTeacher(cells[0]); rows.push({dia:'lunes',inicio:ini,fin:fin,materia:st.materia,docente:st.docente,lugar:'',observacion:'Revise día: el OCR no identificó columna'})} continue;} }
  if(!rows.length){if(showEmpty)toast('No se detectaron filas. Intente una foto más nítida, pegue texto o agregue bloques manualmente.'); return false;}
  reviewParsedSchedule(rows); return true;}
function reviewParsedSchedule(rows){window._parsedSchedule=rows; showModal(`<h2>Revisar horario detectado</h2><p class="subtle">Revise cada fila antes de guardar. El docente o instructor es obligatorio para las clases; si el OCR no lo leyó, complete ese campo antes de guardar.</p><div class="parsed-list">${rows.map((r,i)=>`<div class="card small parsed-row"><div class="grid two"><label>Día<select id="rowDia${i}"><option ${r.dia==='lunes'?'selected':''}>lunes</option><option ${r.dia==='martes'?'selected':''}>martes</option><option ${r.dia==='miercoles'?'selected':''}>miercoles</option><option ${r.dia==='jueves'?'selected':''}>jueves</option><option ${r.dia==='viernes'?'selected':''}>viernes</option><option ${r.dia==='sabado'?'selected':''}>sabado</option><option ${r.dia==='domingo'?'selected':''}>domingo</option></select></label><label>Horario<div class="row"><input id="rowIni${i}" value="${esc(r.inicio)}"><input id="rowFin${i}" value="${esc(r.fin)}"></div></label></div><label>Materia / actividad<input id="rowMat${i}" value="${esc(r.materia)}"></label><label>Docente / instructor<input id="rowDoc${i}" value="${esc(r.docente||'')}"></label><label>Observación<input id="rowObs${i}" value="${esc(r.observacion||'')}"></label></div>`).join('')}</div><div class="form-actions"><button class="btn" onclick="saveParsedSchedule(${rows.length})">Reemplazar horario</button><button class="btn secondary" onclick="appendParsedSchedule(${rows.length})">Crear/Agregar parcial</button><button class="btn ghost" onclick="closeModal()">Cancelar</button></div>`)}
function collectParsedRows(n){return Array.from({length:n},(_,i)=>{const materia=$(`#rowMat${i}`).value.trim(); const docente=$(`#rowDoc${i}`).value.trim(); const tipo=/descanso/i.test(materia)?'descanso':/(parte|hora mística|hora mistica)/i.test(materia)?'formacion':'clase'; return {dia:$(`#rowDia${i}`).value,inicio:$(`#rowIni${i}`).value,fin:$(`#rowFin${i}`).value,materia,docente,lugar:'',observacion:$(`#rowObs${i}`).value,id:uid(),tipo}}).filter(r=>r.materia||r.docente)}
async function saveParsedSchedule(n){if(!confirm('¿Reemplazar el horario actual? El horario anterior quedará en el historial local si existe.'))return; state.scheduleHistory=state.scheduleHistory||[]; if(state.scheduleBlocks?.length) state.scheduleHistory.push({id:uid(),date:new Date().toISOString(),blocks:state.scheduleBlocks,photo:state.schedulePhoto,name:state.schedulePhotoName}); state.scheduleBlocks=collectParsedRows(n); await save(); closeModal(); render(); toast('Horario reemplazado')}
async function appendParsedSchedule(n){state.scheduleBlocks.push(...collectParsedRows(n)); await save(); closeModal(); render(); toast('Horario agregado')}
function openScheduleBlockForm(id=null,day=null){const b=id?state.scheduleBlocks.find(x=>x.id===id):{dia:day||currentDayKey(),inicio:'07:30',fin:'08:10',tipo:'clase',docente:''}; showModal(`<h2>${id?'Editar':'Nuevo'} bloque</h2><form id="blockForm">${buildForm([{name:'dia',label:'Día',type:'select',options:['lunes','martes','miercoles','jueves','viernes','sabado','domingo']},{name:'inicio',label:'Inicio',type:'time'},{name:'fin',label:'Fin',type:'time'},{name:'tipo',label:'Tipo',type:'select',options:['clase','formacion','descanso','actividad']},{name:'materia',label:'Materia / actividad'},{name:'docente',label:'Docente / instructor'},{name:'lugar',label:'Aula / lugar'},{name:'observacion',label:'Observación',type:'textarea'}],b)}<div class="form-actions"><button class="btn" type="submit">Guardar</button>${id?`<button class="btn danger" type="button" onclick="deleteBlock('${id}')">Eliminar</button>`:''}<button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button></div></form>`); $('#blockForm').onsubmit=async e=>{e.preventDefault(); const data=formData(e.target); if(id)Object.assign(b,data); else state.scheduleBlocks.push({...data,id:uid()}); await save(); closeModal(); render()}}
async function deleteBlock(id){if(!confirm('¿Eliminar bloque?'))return; state.scheduleBlocks=state.scheduleBlocks.filter(x=>x.id!==id); await save(); closeModal(); render()}
function openClassDetail(id){const b=state.scheduleBlocks.find(x=>x.id===id); if(!b)return; showModal(`<h2>${esc(b.materia||'Actividad')}</h2><p><b>${esc(b.dia)}</b> · ${esc(b.inicio)} - ${esc(b.fin)}</p><p><b>Docente:</b> ${esc(b.docente||'')}</p><p><b>Lugar:</b> ${esc(b.lugar||'')}</p><p>${esc(b.observacion||'')}</p><button class="btn" onclick="closeModal();openScheduleBlockForm('${b.id}')">Editar</button>`) }
async function doLibrarySearch(q){if(!docs.uniformes){$('#libResults').innerHTML='<div class="card small"><p>Cargando biblioteca normativa...</p></div>'; await loadAllData();} const res=libraryResults(q); $('#libResults').innerHTML=res.length?`<h3>Resultados</h3>${res.slice(0,60).map(r=>`<div class="list-item clickable" onclick="openArticle('${r.doc}','${r.num}')"><span class="tag">${esc(r.docTitle)}</span><h3>${esc(r.title)}</h3><p>${esc(r.snip)}</p>${r.hasImage?'<p class="subtle">🖼️ Incluye imagen del reglamento</p>':''}</div>`).join('')}`:`<div class="card small"><p>No se encontraron resultados. Pruebe con variantes como <b>3A</b>, <b>3-A</b>, <b>Uniforme 3A</b> o <b>Artículo 41</b>.</p></div>`}
function uniformCodeAliases(a){const text=[a.titulo,a.texto,a.codigo,a.alias_busqueda,(a.aliases||[]).join(' '),(a.alias_extra||[]).join(' ')].join(' '); const out=[]; [...text.matchAll(/(?:uniforme\s*)?(?:n[º°.]?\s*)?(0?\d)\s*[-–]?\s*([ab])(?:\s*\(?tropical\)?)?/gi)].forEach(m=>{const n=String(Number(m[1])); const l=m[2].toUpperCase(); out.push(`${n}${l}`,`${n}-${l}`,`${n} ${l}`,`0${n}${l}`,`0${n}-${l}`,`0${n} ${l}`,`uniforme ${n}${l}`,`uniforme ${n}-${l}`,`uniforme 0${n}${l}`); if(/tropical/i.test(m[0])||/tropical/i.test(a.titulo||'')) out.push(`${n}${l} tropical`,`${n}-${l} tropical`,`0${n} ${l} tropical`,`uniforme ${n}${l} tropical`,`uniforme ${n}-${l} tropical`);}); return out}
function articleHasImage(a){return !!(a.pagina_inicio||a.imagen_principal||(a.imagenes_bloque||[]).length||(a.imagenes||[]).length)}
function articleHaystack(a){return [a.numero,a.numero_articulo,a.titulo,a.texto,a.codigo,a.variante,a.alias_busqueda,(a.categorias||[]).join(' '),(a.aliases||[]).join(' '),(a.alias_extra||[]).join(' '),...uniformCodeAliases(a)].join(' ')}
function searchScore(a,q,doc){const nq=normalize(q), compact=nq.replace(/\s+/g,''); let score=0; const title=normalize(a.titulo||''), num=normalize(a.numero||''), text=normalize(a.texto||''); const aliases=uniformCodeAliases(a).map(x=>normalize(x)); if(doc==='uniformes' && aliases.some(x=>x.replace(/\s+/g,'')===compact || x===nq)) score+=140; if(title.includes(nq)||title.replace(/\s+/g,'').includes(compact)) score+=100; if(num.includes(nq)) score+=80; if((a.alias_busqueda||'').toString().toLowerCase().includes(q.toLowerCase())) score+=70; if(text.includes(nq)||text.replace(/\s+/g,'').includes(compact)) score+=25; if(articleHasImage(a)) score+=5; if(/tropical/i.test(a.titulo||'')&&!/tropical/i.test(q)) score-=35; return score}
function libraryResults(q){const out=[]; if(!q)return out; const push=(doc,docTitle,arr)=>arr?.forEach(a=>{const hay=articleHaystack(a); if(contains(hay,q)){const score=searchScore(a,q,doc); out.push({doc,docTitle,num:a.numero,title:`${a.numero} ${a.titulo||''}`,snip:(a.texto||'').replace(/\s+/g,' ').slice(0,190),hasImage:articleHasImage(a),score})}}); push('uniformes','Reglamento de Uniformes',docs.uniformes?.articulos); push('sumario','Reglamento Sumario',docs.sumario?.articulos||docs.sumario?.contenido?.articulos); docs.norms?.forEach((d,i)=>push('norm'+i,d.metadatos?.titulo||d.titulo||d.nombre||'Norma',d.articulos||d.contenido?.articulos)); return out.sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title))}
function searchGlobal(q){go('biblioteca').then(()=>setTimeout(()=>{const inp=$('#libQuery'); if(inp){inp.value=q; doLibrarySearch(q)}},100))}
function openDoc(id){const key=String(id).toLowerCase(); if(key.includes('uniform')) showUniformIndex(); else if(key.includes('sumaria')||key.includes('sumario')) doLibrarySearch('falta'); else doLibrarySearch('artículo')}
function quickSumario(title){doLibrarySearch(title.replace('Faltas ',''));}
function showUniformIndex(){const arts=(docs.uniformes?.articulos||[]).filter(a=>/uniforme/i.test(a.titulo||'')); $('#libResults').innerHTML=`<h3>Uniformes del reglamento</h3>${arts.map(a=>`<div class="list-item clickable" onclick="openArticle('uniformes','${a.numero}')"><span class="tag">Reglamento de Uniformes</span><h3>${esc(a.numero)} ${esc(a.titulo||'')}</h3>${articleHasImage(a)?'<p>🖼️ Ver imagen y ficha completa</p>':'<p>Ficha sin imagen asociada pendiente de revisión visual.</p>'}</div>`).join('')}`}
function articleImages(art){const list=[]; (art.imagenes_bloque||[]).forEach(x=>list.push(x)); if(art.imagen_principal) list.push(art.imagen_principal); (art.imagenes||[]).forEach(x=>list.push(x)); (art.imagenes_asociadas||[]).forEach(x=>{ if(typeof x==='string'&&x.match(/\.(png|jpg|jpeg|webp)$/i)) list.push(x) }); return [...new Set(list.filter(Boolean))]}
function articlePageImages(art){const n=Number(art.numero_articulo||String(art.numero||'').match(/\d+/)?.[0]||0); if(n>=36&&n<=52)return [`assets/uniformes/bloques/art-${n}-bloque.jpg`]; return articleImages(art)}
function pdfLinkFor(doc,art){if(doc==='uniformes')return `./assets/reglamento-uniformes-2021.pdf${art.pagina_inicio?'#page='+encodeURIComponent(art.pagina_inicio):''}`; if(doc==='sumario')return ''; if(doc.startsWith('norm')){const idx=+doc.replace('norm',''); const d=docs.norms[idx]; return d?.pdf||d?.fuente_pdf||''} return ''}
function openArticle(doc,num){let art, title=''; if(doc==='uniformes'){art=docs.uniformes.articulos.find(a=>a.numero===num); title='Reglamento de Uniformes'} else if(doc==='sumario'){const arr=docs.sumario?.articulos||docs.sumario?.contenido?.articulos; art=arr.find(a=>a.numero===num); title='Reglamento Sumario'} else if(doc.startsWith('norm')){const d=docs.norms[+doc.replace('norm','')]; const arr=d.articulos||d.contenido?.articulos; art=arr?.find(a=>a.numero===num); title=d.metadatos?.titulo||d.titulo||'Norma'} if(!art)return; const link=pdfLinkFor(doc,art); const pageList=doc==='uniformes'?articlePageImages(art):[]; const pageImgs=pageList.map(src=>`<figure class=\"pdf-page-figure\"><img src=\"./${src}\" loading=\"lazy\" onclick=\"openImageFull('./${src}')\" onerror=\"this.closest('figure').classList.add('img-error')\"><figcaption>${src.includes('/bloques/')?'Bloque visual completo del artículo':'Página '+esc(src.match(/pagina-(\d+)/)?.[1]||'')}</figcaption></figure>`).join(''); const extraImgs=doc==='uniformes'?articleImages(art).filter(x=>!pageList.includes(x)).map(src=>`<figure class=\"uniform-figure\"><img src=\"./${src}\" loading=\"lazy\" onerror=\"this.closest('figure').classList.add('img-error')\"><figcaption>${esc(src.split('/').pop())}</figcaption></figure>`).join(''):''; showModal(`<button class=\"icon-btn close\" onclick=\"closeModal()\">×</button><p class=\"tag\">${esc(title)}</p><h2>${esc(art.numero)} ${esc(art.titulo||'')}</h2><div class=\"article-actions\">${link?`<a class=\"btn important link-btn\" href=\"${esc(link)}\" target=\"_blank\" rel=\"noopener\">Ver documento original PDF</a>`:''}${doc==='uniformes'?`<button class=\"btn ghost\" onclick=\"auditUniformImages('${esc(art.numero)}')\">Auditar imágenes</button>`:''}</div>${doc==='uniformes'?`<div class=\"card small visual-rule\"><b>Visual literal del artículo</b><p>Se muestra el bloque visual consolidado del artículo, tomado del PDF original: título, descripción y capturas/fotografías asociadas hasta antes del siguiente artículo.</p></div>${pageImgs?`<div class=\"pdf-page-stack\">${pageImgs}</div>`:'<div class=\"card small warn-card\"><p>No hay captura de página disponible. Use Ver documento original PDF.</p></div>'}${extraImgs?`<details class=\"card\"><summary><b>Imágenes recortadas complementarias</b></summary><div class=\"uniform-imgs\">${extraImgs}</div></details>`:''}`:''}<div class=\"article-text\">${formatArticleText(art.texto||'')}</div>${art.pagina_inicio?`<p class=\"subtle\">Página original: ${art.pagina_inicio}${art.pagina_fin&&art.pagina_fin!==art.pagina_inicio?' a '+art.pagina_fin:''}</p>`:''}${doc!=='uniformes'&&link?`<p><a class=\"btn important\" href=\"${esc(link)}\" target=\"_blank\" rel=\"noopener\">Ver documento original PDF</a></p>`:''}`)}
function openImageFull(src){showModal(`<button class=\"icon-btn close\" onclick=\"closeModal()\">×</button><img src=\"${esc(src)}\" class=\"image-preview full-page-preview\"><p class=\"subtle\">Toque cerrar para volver.</p>`)}
function formatArticleText(text){if(!text)return ''; const parts=String(text).split(/(?=\s(?:\d{1,2}|[a-z])\.\s+)/g).map(x=>x.trim()).filter(Boolean); if(parts.length>1){return `<div class="num-list">${parts.map(p=>{const m=p.match(/^([\da-z]+)\.\s*(.*)/i); return m?`<div class="num-entry"><strong>${esc(m[1])}</strong><span>${esc(m[2])}</span></div>`:`<p>${esc(p)}</p>`}).join('')}</div>`} return esc(text)}
function openKardex(){showModal(`<h2>Ficha Kardex</h2><p class="subtle">Datos voluntarios. No se cargan datos reales por defecto.</p><textarea id="kardexText" style="width:100%;min-height:140px" placeholder="Pegar texto de identificación..."></textarea><button class="btn secondary" onclick="parseKardex()">Interpretar texto</button><form id="kardexForm">${buildForm(['numeroLista','grado','nombre','ci','expedido','escalafon','celular','fechaNacimiento','edad','tipoSangre','numAsegurado','numEmpleador','domicilio','correo'].map(n=>({name:n,label:n.replace(/[A-Z]/g,m=>' '+m).replace(/^./,c=>c.toUpperCase())})),state.kardex.fields)}<div class="form-actions"><button class="btn" type="submit">Guardar</button><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button></div></form>`); $('#kardexText').value=state.kardex.sourceText||''; $('#kardexForm').onsubmit=async e=>{e.preventDefault(); state.kardex.fields=formData(e.target); state.kardex.sourceText=$('#kardexText').value; await save(); closeModal(); toast('Kardex guardado')}}
function parseKardex(){const t=$('#kardexText').value; const map={numeroLista:/n[uú]mero de lista\s*([\w-]+)/i,nombre:/nombre\s+(.+)/i,grado:/(CAP\.|SGTO\.|SOF\.|TCNL\.|CNL\.)/i,ci:/c\.?i\.?\s*([^\n]+)/i,escalafon:/esc\.?\s*([^\n]+)/i,celular:/cel\.?\s*([^\n]+)/i,fechaNacimiento:/nac\.?\s*([^\n]+)/i,tipoSangre:/tipo de sangre\s*([^\n]+)/i,numAsegurado:/asegurado\s*([^\n]+)/i,numEmpleador:/empleador\s*([^\n]+)/i,domicilio:/domicilio\s*([^\n]+)/i,correo:/correo\s*([^\n]+)/i,edad:/edad\.?\s*([^\n]+)/i}; Object.entries(map).forEach(([k,r])=>{const m=t.match(r); if(m){const el=$(`[name="${k}"]`); if(el)el.value=(m[1]||m[0]).trim()}})}
function showUpdateBanner(){const b=$('#updateBanner'); if(b)b.classList.remove('hidden')}
function rememberLocalBackup(){try{localStorage.setItem('agenda-policial-last-backup',JSON.stringify({version:APP_VERSION,date:new Date().toISOString(),state}))}catch(e){console.warn(e)}}
function installMode(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone?'PWA instalada':'Navegador'}
async function cacheNames(){return 'caches' in window ? await caches.keys() : []}
async function applyUpdate(){toast('Aplicando actualización...'); rememberLocalBackup(); try{const reg=await navigator.serviceWorker?.getRegistration?.(); if(reg){await reg.update().catch(()=>{}); if(reg.waiting){reg.waiting.postMessage({type:'SKIP_WAITING'}); return}} await cleanAppCaches(false); location.replace('./index.html?v='+APP_VERSION+'&r='+Date.now())}catch(e){console.warn(e); location.replace('./index.html?v='+APP_VERSION+'&r='+Date.now())}}
async function checkUpdate(){toast('Buscando actualización...'); rememberLocalBackup(); state.settings.lastUpdateCheck=new Date().toISOString(); await save(); if('serviceWorker' in navigator) navigator.serviceWorker.getRegistration().then(r=>r&&r.update()).catch(()=>{}); fetch('./version.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.json()).then(v=>{if(v.version&&v.version!==APP_VERSION){showUpdateBanner(); toast('Nueva versión disponible: '+v.version)} else toast('La versión publicada coincide: '+APP_VERSION)}).catch(()=>toast('No se pudo comprobar. Revise conexión o GitHub Pages.'))}
async function cleanAppCaches(show=true){if(!('caches' in window)){if(show)toast('Este navegador no expone caché'); return} const keys=await caches.keys(); await Promise.all(keys.filter(k=>k.startsWith('agenda-policial')).map(k=>caches.delete(k))); if(show)toast('Caché limpiado sin borrar sus datos')}
async function forceCleanUpdate(){if(!confirm('Se limpiará caché de la app sin borrar sus datos. Luego se recargará desde GitHub. ¿Continuar?'))return; rememberLocalBackup(); state.settings.lastCleanUpdate=new Date().toISOString(); await save(); await cleanAppCaches(false); const regs=await navigator.serviceWorker?.getRegistrations?.()||[]; await Promise.all(regs.filter(r=>String(r.scope).includes(location.pathname.split('/').filter(Boolean)[0])||String(r.scope).includes('Poli.Agenda_pro')).map(r=>r.update().catch(()=>{}))); location.replace('./index.html?clean=1&v='+APP_VERSION+'&r='+Date.now())}
async function openDiagnostics(){const keys=await cacheNames(); const reg=await navigator.serviceWorker?.getRegistration?.(); const rows=[['Versión visible',APP_VERSION],['Compilación',BUILD_DATE],['URL',location.href],['Modo',state.mode||'sin modo'],['Instalación',installMode()],['Activación',state.activated?'activa':'no activa'],['Service Worker',reg?(reg.active?'activo':reg.waiting?'esperando':'registrado'):'no registrado'],['Cachés',keys.join(', ')||'sin caché'],['Registros locales',`${state.formations.length} formaciones · ${state.tasks.length} tareas · ${state.notes.length} notas · ${state.scheduleBlocks.length} bloques horario`],['Última revisión',state.settings.lastUpdateCheck||'sin revisión']]; showModal(`<button class="icon-btn close" onclick="closeModal()">×</button><h2>Estado técnico</h2><div class="diagnostic-table">${rows.map(r=>`<div><b>${esc(r[0])}</b><span>${esc(r[1])}</span></div>`).join('')}</div><div class="row wrap"><button class="btn important" onclick="forceCleanUpdate()">Forzar actualización limpia</button><button class="btn secondary" onclick="cleanAppCaches()">Limpiar caché</button><button class="btn ghost" onclick="exportBackup()">Exportar respaldo</button></div>`)}
async function auditUniformImages(articleNum=''){if(!docs.uniformes) await loadAllData(); const arts=(docs.uniformes?.articulos||[]).filter(a=>!articleNum||a.numero===articleNum); const items=[]; for(const a of arts){for(const src of articleImages(a)){items.push({article:a.numero,title:a.titulo||'',src})}} if(!items.length){toast('No hay imágenes declaradas para auditar'); return} showModal(`<button class="icon-btn close" onclick="closeModal()">×</button><h2>Auditoría de imágenes</h2><p class="subtle">Verificando rutas locales de uniformes...</p><div id="auditImageResults" class="audit-list"><p>Procesando ${items.length} imagen(es)...</p></div>`); const results=[]; for(const it of items){let ok=false; try{const r=await fetch('./'+it.src,{cache:'no-store'}); ok=r.ok}catch(e){ok=false} results.push({...it,ok})} const bad=results.filter(x=>!x.ok); const el=$('#auditImageResults'); if(el) el.innerHTML=`<div class="status-grid"><div><b>Total</b><span>${results.length}</span></div><div><b>Correctas</b><span>${results.length-bad.length}</span></div><div><b>Faltantes</b><span>${bad.length}</span></div></div>${results.map(r=>`<div class="audit-row ${r.ok?'ok':'bad'}"><b>${esc(r.article)}</b><span>${r.ok?'✓':'⚠'} ${esc(r.src)}</span></div>`).join('')}`; toast(bad.length?`Hay ${bad.length} imagen(es) con problema`:'Imágenes verificadas correctamente')}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='agenda-policial-respaldo.json'; a.click(); state.settings.lastBackup=new Date().toISOString(); save()}
function importBackup(){const input=$('#backupImport'); input.onchange=e=>{const f=e.target.files[0]; if(!f)return; const rd=new FileReader(); rd.onload=async()=>{try{const data=JSON.parse(rd.result); if(confirm('¿Reemplazar datos actuales por el respaldo?')){state={...structuredClone(DEFAULT_STATE),...data}; await save(); closeModal(); render(); toast('Respaldo importado')}}catch{toast('Archivo inválido')}}; rd.readAsText(f)}; input.click()}
window.addEventListener('DOMContentLoaded',init);
