const DB='poliagenda-db', STORE='kv'; let uniformes=null,sumario=null,state={view:'home',q:''};
const $=s=>document.querySelector(s), app=$('#app');
const now=()=>new Date().toISOString();
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbGet(k,d){const db=await openDB();return new Promise(res=>{const tx=db.transaction(STORE,'readonly'), st=tx.objectStore(STORE), rq=st.get(k);rq.onsuccess=()=>res(rq.result??d);rq.onerror=()=>res(d)})}
async function dbSet(k,v){const db=await openDB();return new Promise(res=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=()=>res(true)})}
async function init(){if('serviceWorker'in navigator) navigator.serviceWorker.register('./sw.js'); uniformes=await fetch('./data/reglamento-uniformes.json').then(r=>r.json()); sumario=await fetch('./data/reglamento-sumario-unipol.json').then(r=>r.json()); render()}
function nav(v){state.view=v; render()}
function hdr(){return `<header><div class=top><div class=brand><h1>PoliAgenda Pro</h1><p>Biblioteca, agenda y asistente policial offline</p></div><span class=pill>${new Date().toLocaleDateString('es-BO')}</span></div><div class=search><input id=q placeholder="Buscar: uniforme, artículo 55, formación, pendiente..." value="${state.q}" oninput="state.q=this.value; renderBody()"></div></header><div class=nav><button onclick="nav('home')">Hoy</button><button class=secondary onclick="nav('biblioteca')">Biblioteca</button><button class=secondary onclick="nav('agenda')">Agenda</button><button class=secondary onclick="nav('analizador')">Analizar comunicado</button><button class=secondary onclick="nav('pendientes')">Pendientes</button><button class=secondary onclick="nav('portfolio')">Portafolio</button><button class=secondary onclick="nav('backup')">Respaldo</button></div>`}
function render(){app.innerHTML=hdr()+`<main class=wrap id=body></main>`; renderBody()}
async function renderBody(){const b=$('#body'); if(!b)return; const q=(state.q||'').toLowerCase().trim(); if(q){b.innerHTML=searchView(q); return} if(state.view==='home') b.innerHTML=await home(); if(state.view==='biblioteca') b.innerHTML=biblioteca(); if(state.view==='agenda') b.innerHTML=await agenda(); if(state.view==='analizador') b.innerHTML=analizador(); if(state.view==='pendientes') b.innerHTML=await pendientes(); if(state.view==='portfolio') b.innerHTML=await portfolio(); if(state.view==='backup') b.innerHTML=backup()}
async function home(){const p=await dbGet('pendientes',[]), ag=await dbGet('agenda',[]); const today=new Date().toISOString().slice(0,10); return `<div class=grid><div class=card><h3>👔 Uniforme del día</h3><p>${(ag.find(x=>x.fecha===today&&x.uniforme)||{}).uniforme||'Sin registrar'}</p></div><div class=card><h3>📍 Formación</h3><p>${(ag.find(x=>x.fecha===today&&x.tipo==='formacion')||{}).hora||'Sin hora'}<br><small>${(ag.find(x=>x.fecha===today&&x.tipo==='formacion')||{}).lugar||'Lugar no registrado'}</small></p></div><div class=card><h3>✅ Pendientes</h3><p>${p.filter(x=>!x.done).length} pendientes</p></div><div class=card><h3>📚 Reglamentos</h3><p>${uniformes.metadatos.paginas_totales} páginas uniformes<br>${sumario.metadatos.articulos_totales} artículos sumario</p></div></div><h2>Acceso rápido</h2><div class=toolbar><button class=btn onclick="nav('analizador')">Pegar comunicado</button><button class=btn onclick="nav('pendientes')">Nuevo pendiente</button><button class=btn onclick="nav('biblioteca')">Buscar reglamento</button></div>`}
function biblioteca(){return `<div class=grid><div class=card onclick="showDoc('uniformes')"><h3>📘 Reglamento de Uniformes</h3><p>Texto, páginas originales e imágenes del PDF.</p><small>${uniformes.metadatos.articulos_detectados} artículos detectados + ${uniformes.paginas.length} páginas consultables.</small></div><div class=card onclick="showDoc('sumario')"><h3>⚖️ Comisión Sumaria UNIPOL</h3><p>Artículos 1 al 92 y disposiciones finales.</p><small>JSON aprobado estructuralmente.</small></div><div class=card onclick="showPages()"><h3>🖼️ Páginas originales</h3><p>Visual del reglamento de uniformes.</p></div><div class=card><h3>⭐ Favoritos</h3><p>Preparado para artículos frecuentes.</p></div></div><div id=list></div>`}
function showDoc(t){const arr=t==='uniformes'?uniformes.articulos:sumario.articulos; $('#list').innerHTML=`<h2>${t==='uniformes'?'Reglamento de Uniformes':'Reglamento Sumario UNIPOL'}</h2><div class=list>${arr.map(a=>`<div class=item onclick='detail(${JSON.stringify(t)},${JSON.stringify(a.id)})'><b>${a.numero} – ${a.titulo}</b><p>${(a.texto||'').slice(0,220)}...</p></div>`).join('')}</div>`}
function showPages(){ $('#list').innerHTML=`<h2>Páginas originales</h2><div class=list>${uniformes.paginas.slice(0,121).map(p=>`<div class=item><b>Página ${p.page}</b><p>${(p.text||'').slice(0,180)}</p><img class=pageimg loading=lazy src='${p.image}'></div>`).join('')}</div>`}
function detail(t,id){const a=(t==='uniformes'?uniformes.articulos:sumario.articulos).find(x=>x.id===id); const imgs=(a.imagenes_asociadas||[]).map(i=>`<img class=pageimg src='${i}'>`).join(''); modal(`<h2>${a.numero} – ${a.titulo}</h2><p style="white-space:pre-wrap">${a.texto}</p>${imgs}<button class=btn onclick="closeModal()">Cerrar</button>`) }
function searchView(q){let res=[]; for(const a of uniformes.articulos) if(JSON.stringify(a).toLowerCase().includes(q)) res.push(a); for(const a of sumario.articulos) if(JSON.stringify(a).toLowerCase().includes(q)) res.push(a); for(const p of uniformes.paginas) if((p.text||'').toLowerCase().includes(q)) res.push({numero:'Página '+p.page,titulo:'Reglamento de Uniformes',texto:(p.text||'').slice(0,500),imagenes_asociadas:[p.image]}); return `<h2>Resultados: ${res.length}</h2><div class=list>${res.slice(0,80).map(a=>`<div class=item><b>${a.numero} – ${a.titulo}</b><p>${(a.texto||'').slice(0,260)}...</p>${(a.imagenes_asociadas||[])[0]?`<img class=pageimg loading=lazy src='${a.imagenes_asociadas[0]}'>`:''}</div>`).join('')}</div>`}
async function agenda(){
 const ag=await dbGet('agenda',[]), semana=await dbGet('horarioSemanal',[]), hist=await dbGet('historialHorarios',[]);
 return `<div class=grid>
  <div class=card><h3>📌 Orden del día / Formación</h3><p class=muted>Para uniforme, formación, parte, lugar y observaciones del día.</p>
   <div class=row><input id=af type=date><input id=ah type=time title="Hora de formación"></div>
   <div class=row><input id=aarr type=time title="Hora de arribo/control"><input id=aparte type=time title="Hora de parte"></div>
   <div class=row><select id=at><option value=formacion>Formación</option><option value=clase>Clase</option><option value=servicio>Servicio</option><option value=actividad>Actividad</option><option value=uniforme>Uniforme del día</option></select><input id=au placeholder="Uniforme: 3A, 3B, aulas con chamarra..."></div>
   <input id=al placeholder="Lugar de formación / aula / ubicación">
   <input id=alink placeholder="Link de ubicación, si lo mandan por WhatsApp">
   <textarea id=ao placeholder="Observaciones: llegar 15 min antes, prendas, comandante presente, etc."></textarea>
   <button class=btn onclick="saveAgenda()">Guardar orden del día</button>
  </div>
  <div class=card><h3>📚 Horario semanal fijo</h3><p class=muted>Se mantiene hasta que lo actualices. Útil para materias del parcial.</p>
   <div class=row><select id=wd><option>Lunes</option><option>Martes</option><option>Miércoles</option><option>Jueves</option><option>Viernes</option><option>Sábado</option><option>Domingo</option></select><input id=wi type=time></div>
   <div class=row><input id=wf type=time><input id=wm placeholder="Materia / actividad"></div>
   <input id=wdoc placeholder="Docente / instructor">
   <input id=wl placeholder="Aula / lugar">
   <input id=wu placeholder="Uniforme requerido, si aplica">
   <textarea id=wo placeholder="Observaciones"></textarea>
   <button class=btn onclick="saveWeekly()">Agregar al horario</button>
  </div>
 </div>
 <div class=toolbar><button class=btn onclick="saveScheduleHistory()">Guardar horario actual como historial</button><button class=btn secondary onclick="clearWeekly()">Limpiar horario semanal</button></div>
 <h2>Hoy y próximos registros</h2><div class=list>${ag.map((x,i)=>`<div class=item><b>${x.fecha||'Sin fecha'} ${x.hora||''} – ${x.tipo}</b><p><b>Arribo:</b> ${x.arribo||'-'} | <b>Parte:</b> ${x.parte||'-'}<br><b>Lugar:</b> ${x.lugar||'No registrado'} ${x.link?`<br><a href="${x.link}" target="_blank">Abrir ubicación</a>`:''}<br><b>Uniforme:</b> ${x.uniforme||'-'}<br>${x.obs||''}</p><button class=btn danger onclick="delAgenda(${i})">Borrar</button></div>`).join('')||'<div class=item>Sin órdenes cargadas.</div>'}</div>
 <h2>Horario semanal vigente</h2><div class=list>${semana.map((x,i)=>`<div class=item><b>${x.dia} ${x.inicio||''}-${x.fin||''} — ${x.materia}</b><p>${x.docente||''}<br>${x.lugar||''}<br>${x.uniforme?`Uniforme: ${x.uniforme}<br>`:''}${x.obs||''}</p><button class=btn danger onclick="delWeekly(${i})">Borrar</button></div>`).join('')||'<div class=item>Sin horario semanal cargado.</div>'}</div>
 <h2>Historial referencial</h2><div class=list>${hist.map((h,i)=>`<div class=item><b>${h.nombre}</b><p>Guardado: ${new Date(h.created).toLocaleString('es-BO')} — ${h.items.length} registros</p><button class=btn onclick="viewHistory(${i})">Ver</button></div>`).join('')||'<div class=item>Sin historial guardado.</div>'}</div>`
}
async function saveAgenda(){let ag=await dbGet('agenda',[]); ag.push({fecha:$('#af').value,hora:$('#ah').value,arribo:$('#aarr').value,parte:$('#aparte').value,tipo:$('#at').value,uniforme:$('#au').value,lugar:$('#al').value,link:$('#alink').value,obs:$('#ao').value,created:now()}); await dbSet('agenda',ag); renderBody()}
async function delAgenda(i){let ag=await dbGet('agenda',[]); ag.splice(i,1); await dbSet('agenda',ag); renderBody()}
async function saveWeekly(){let w=await dbGet('horarioSemanal',[]); w.push({dia:$('#wd').value,inicio:$('#wi').value,fin:$('#wf').value,materia:$('#wm').value,docente:$('#wdoc').value,lugar:$('#wl').value,uniforme:$('#wu').value,obs:$('#wo').value,created:now()}); await dbSet('horarioSemanal',w); renderBody()}
async function delWeekly(i){let w=await dbGet('horarioSemanal',[]); w.splice(i,1); await dbSet('horarioSemanal',w); renderBody()}
async function clearWeekly(){if(!confirm('¿Limpiar todo el horario semanal vigente? Antes puedes guardarlo como historial.'))return; await dbSet('horarioSemanal',[]); renderBody()}
async function saveScheduleHistory(){let w=await dbGet('horarioSemanal',[]); if(!w.length)return alert('No hay horario semanal para guardar.'); const nombre=prompt('Nombre del historial. Ej.: Primer parcial, Segundo parcial')||('Historial '+new Date().toLocaleDateString('es-BO')); let h=await dbGet('historialHorarios',[]); h.unshift({nombre,items:w,created:now()}); await dbSet('historialHorarios',h); alert('Horario guardado como historial referencial.')}
async function viewHistory(i){const h=(await dbGet('historialHorarios',[]))[i]; modal(`<h2>${h.nombre}</h2><div class=list>${h.items.map(x=>`<div class=item><b>${x.dia} ${x.inicio||''}-${x.fin||''} — ${x.materia}</b><p>${x.docente||''}<br>${x.lugar||''}<br>${x.uniforme||''}<br>${x.obs||''}</p></div>`).join('')}</div><button class=btn onclick="closeModal()">Cerrar</button>`)}
function analizador(){return `<div class=card><h3>Analizador de comunicados</h3><p class=muted>Pega mensajes de WhatsApp, órdenes, servicios o comunicados. La app detecta fecha, hora, lugar, uniforme, pendiente y rectificaciones.</p><textarea id=comm placeholder="Pega aquí el comunicado..."></textarea><button class=btn onclick="parseComm()">Analizar</button></div><div id=parseout></div>`}
function parseComm(){const t=$('#comm').value; const low=t.toLowerCase(); const times=[...t.matchAll(/(\d{1,2}:\d{2})/g)].map(x=>x[1]); const date=(t.match(/(lunes|martes|miércoles|miercoles|jueves|viernes|sábado|sabado|domingo)[^\n]*/i)||[])[0]||''; const lugar=(t.match(/lugar[:*\s]*([^\n]+)/i)||[])[1]||''; const uniforme=(t.match(/uniforme[^\n:]*[:\s]*([^\n]+)/i)||[])[1]||''; const rect=/rectificando|modificando|postergando|suspendiendo|nueva hora|cambio/i.test(t); const pendiente=/fecha límite|presentación|entrega|depósito|boleta|fotocopia|certificado/i.test(t); const tipo=pendiente?'pendiente':/orden de guarnicion|servicio|planeamiento|operaciones/i.test(low)?'servicio':'formacion'; $('#parseout').innerHTML=`<div class=card urgent><h3>Resultado detectado</h3><span class=badge>${tipo}</span>${rect?'<span class=badge>Actualización / rectificación</span>':''}<p><b>Fecha:</b> ${date||'No detectada'}<br><b>Horas:</b> ${times.join(', ')||'No detectadas'}<br><b>Lugar:</b> ${lugar||'No detectado'}<br><b>Uniforme:</b> ${uniforme||'No detectado'}</p><button class=btn onclick="saveParsed('${tipo}',${JSON.stringify(t).replace(/"/g,'&quot;')})">Guardar como ${tipo}</button></div>`}
async function saveParsed(tipo,raw){ if(tipo==='pendiente'){let p=await dbGet('pendientes',[]);p.push({title:raw.slice(0,80),date:'',time:'',prio:'Urgente',obs:raw,done:false,created:now()});await dbSet('pendientes',p);nav('pendientes')} else {let ag=await dbGet('agenda',[]);ag.push({fecha:'',hora:'',tipo,lugar:'',uniforme:'',obs:raw,created:now()});await dbSet('agenda',ag);nav('agenda')}}
async function pendientes(){const p=await dbGet('pendientes',[]); return `<div class=card><h3>Nuevo pendiente rápido</h3><input id=pt placeholder="Ej.: Presentar fotocopia de CI"><div class=row><input id=pd type=date><input id=ph type=time></div><select id=pp><option>Normal</option><option>Importante</option><option>Urgente</option></select><textarea id=po placeholder="Observación"></textarea><button class=btn onclick="addPend()">Guardar</button></div><h2>Pendientes</h2><div class=list>${p.map((x,i)=>`<div class="item ${x.done?'done':''}" onclick="togglePend(${i})"><b>${x.done?'✅':'☐'} ${x.title}</b><p>${x.date||''} ${x.time||''} <span class=badge>${x.prio||'Normal'}</span><br>${x.obs||''}</p></div>`).join('')}</div>`}
async function addPend(){let p=await dbGet('pendientes',[]);p.push({title:$('#pt').value,date:$('#pd').value,time:$('#ph').value,prio:$('#pp').value,obs:$('#po').value,done:false,created:now()});await dbSet('pendientes',p);renderBody()}
async function togglePend(i){let p=await dbGet('pendientes',[]);p[i].done=!p[i].done;await dbSet('pendientes',p);renderBody()}
async function portfolio(){const pin=await dbGet('pin',null); if(!pin)return `<div class=card><h3>Crear PIN de 4 dígitos</h3><input id=pin maxlength=4 inputmode=numeric><button class=btn onclick="setPin()">Guardar PIN</button></div>`; return `<div class=card><h3>Portafolio personal protegido</h3><input id=pintry maxlength=4 inputmode=numeric placeholder="PIN"><button class=btn onclick="unlockPortfolio()">Ingresar</button></div><div id=port></div>`}
async function setPin(){if($('#pin').value.length!==4)return alert('PIN debe tener 4 dígitos'); await dbSet('pin',$('#pin').value); renderBody()}
async function unlockPortfolio(){if($('#pintry').value!==await dbGet('pin',null))return alert('PIN incorrecto'); const docs=await dbGet('docs',[]); $('#port').innerHTML=`<div class=card><input id=dn placeholder="Documento / dato"><textarea id=dd placeholder="Detalle, número, vencimiento u observación"></textarea><button class=btn onclick="addDoc()">Guardar dato</button></div><div class=list>${docs.map(d=>`<div class=item><b>${d.name}</b><p>${d.detail}</p></div>`).join('')}</div>`}
async function addDoc(){let d=await dbGet('docs',[]);d.push({name:$('#dn').value,detail:$('#dd').value,created:now()});await dbSet('docs',d);unlockPortfolio()}
function backup(){return `<div class=card><h3>Respaldos</h3><p>Exporta e importa todos los datos locales para evitar pérdidas.</p><button class=btn onclick="exportBackup()">Exportar respaldo JSON</button><input type=file id=importer accept=.json onchange="importBackup(event)"></div>`}
async function exportBackup(){const data={agenda:await dbGet('agenda',[]),pendientes:await dbGet('pendientes',[]),docs:await dbGet('docs',[]),horarioSemanal:await dbGet('horarioSemanal',[]),historialHorarios:await dbGet('historialHorarios',[]),pin:await dbGet('pin',null),exported:now()}; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); a.download='respaldo-poliagenda.json'; a.click(); await dbSet('lastBackup',now())}
async function importBackup(e){const f=e.target.files[0]; if(!f)return; if(!confirm('Esto reemplazará agenda, pendientes y portafolio. ¿Continuar?'))return; const data=JSON.parse(await f.text()); for(const k of ['agenda','pendientes','docs','horarioSemanal','historialHorarios','pin']) if(k in data) await dbSet(k,data[k]); alert('Respaldo importado'); renderBody()}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class=modal id=modal><div class=modalbox>${html}</div></div>`)} function closeModal(){document.getElementById('modal')?.remove()}
init();
