(()=>{
'use strict';
const VERSION='2.21.19';
const CACHE_KEY='agenda-birthdays-v22119';
let rows=[];
let courseCode=null;
let modalTab='today';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digits=s=>String(s||'').replace(/\D/g,'');
const intl=s=>{const d=digits(s);return d.startsWith('591')?d:(d.length===8?'591'+d:d)};
function session(){try{return typeof academicSession!=='undefined'&&academicSession?academicSession:JSON.parse(localStorage.getItem('agenda-academic-session')||'null')}catch{return null}}
function detectCourse(){const s=session();if(s?.course_code)return s.course_code;const selected=[...document.querySelectorAll('select')].find(x=>/capitanes\s*[ab]/i.test(x.selectedOptions?.[0]?.textContent||''));const txt=selected?.selectedOptions?.[0]?.textContent||'';if(/capitanes\s*b/i.test(txt))return 'capitanes-b-2026-2';if(/capitanes\s*a/i.test(txt))return 'capitanes-a-2026-2';return 'capitanes-a-2026-2'}
function todayLocal(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function occurrence(md,base=todayLocal()){const m=Number(md?.slice(0,2)),day=Number(md?.slice(3,5));if(!m||!day)return null;let y=base.getFullYear(),x=new Date(y,m-1,day);if(x<base)x=new Date(y+1,m-1,day);return x}
function daysUntil(md){const a=todayLocal(),b=occurrence(md,a);return b?Math.round((b-a)/86400000):999}
function dateLabel(md){const m=Number(md?.slice(0,2)),d=Number(md?.slice(3,5));const months=['ENE','FEB','MAR','ABR','MAY','JUN','JUL','AGO','SEP','OCT','NOV','DIC'];return `${String(d).padStart(2,'0')} ${months[m-1]||''}`}
function shortName(n=''){const p=String(n).trim().split(/\s+/);if(p.length<=3)return p.join(' ');return p.slice(0,3).join(' ')}
function sorted(){return [...rows].sort((a,b)=>daysUntil(a.birthday_md)-daysUntil(b.birthday_md)||String(a.full_name).localeCompare(String(b.full_name),'es'))}
function todayRows(){return rows.filter(r=>daysUntil(r.birthday_md)===0)}
function weekRows(){return sorted().filter(r=>daysUntil(r.birthday_md)>=0&&daysUntil(r.birthday_md)<=7)}
function monthRows(){const now=new Date(),m=now.getMonth()+1;return rows.filter(r=>Number(r.birthday_md?.slice(0,2))===m).sort((a,b)=>Number(a.birthday_md.slice(3,5))-Number(b.birthday_md.slice(3,5)))}
function nextRows(){const s=sorted();if(!s.length)return[];const d=daysUntil(s[0].birthday_md);return s.filter(r=>daysUntil(r.birthday_md)===d)}
function saveCache(){try{localStorage.setItem(CACHE_KEY,JSON.stringify({courseCode,rows,ts:Date.now()}))}catch{}}
function loadCache(){try{const c=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');if(c?.rows?.length){rows=c.rows;courseCode=c.courseCode||courseCode;return true}}catch{}return false}
async function load(force=false){courseCode=detectCourse();if(!force&&loadCache()&&rows.length){renderAll();}
 if(typeof window.academicRPC!=='function'||!navigator.onLine){renderAll();return rows}
 try{const r=await window.academicRPC('academic_birthdays',{p_course_code:courseCode});if(Array.isArray(r)){rows=r;saveCache();renderAll()}}catch(e){console.warn('Cumpleaños: usando caché local',e);renderAll()}
 return rows}
function ensureStyles(){if(document.getElementById('birthday22119Styles'))return;const s=document.createElement('style');s.id='birthday22119Styles';s.textContent=`
.ap-bday-chip{display:inline-flex;align-items:center;gap:6px;margin-top:7px;border:1px solid rgba(255,255,255,.24);background:rgba(255,255,255,.12);color:#fff;border-radius:999px;padding:5px 9px;font:inherit;max-width:100%;box-shadow:inset 0 1px 0 rgba(255,255,255,.09)}.ap-bday-chip .cake{font-size:15px}.ap-bday-chip b{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:230px}.ap-bday-chip.today{background:linear-gradient(135deg,rgba(214,171,56,.30),rgba(255,255,255,.13));border-color:rgba(247,215,120,.60)}
.ap-bday-card{margin:10px 0 14px;padding:14px 15px;border-radius:20px;border:1px solid #d8c47a;background:linear-gradient(135deg,#fffdf3,#f2f7ef);display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:11px;align-items:center;box-shadow:0 8px 22px rgba(30,55,35,.08)}.ap-bday-card .ico{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;background:#fff3c9;font-size:22px}.ap-bday-card b{display:block;font-size:14px;color:#263c2d}.ap-bday-card small{display:block;margin-top:3px;color:#6e756f}.ap-bday-card .open{border:0;background:#254f31;color:#fff;border-radius:12px;padding:9px 11px;font-weight:800}
.ap-bday-modal{position:fixed;inset:0;z-index:90}.ap-bday-back{position:absolute;inset:0;background:rgba(0,0,0,.42)}.ap-bday-sheet{position:absolute;left:0;right:0;bottom:0;max-height:88dvh;overflow:auto;background:#f8faf7;border-radius:28px 28px 0 0;padding:18px 16px calc(20px + env(safe-area-inset-bottom));box-shadow:0 -18px 50px rgba(0,0,0,.25)}.ap-bday-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.ap-bday-head h2{margin:0;font-size:24px}.ap-bday-close{border:0;width:38px;height:38px;border-radius:13px;background:#e8eee9;font-size:24px;color:#23442e}.ap-bday-tabs{display:flex;gap:7px;overflow:auto;margin:15px 0 12px}.ap-bday-tabs button{border:1px solid #d7e0d8;background:#fff;border-radius:999px;padding:8px 11px;font-weight:800;color:#546258;white-space:nowrap}.ap-bday-tabs button.active{background:#254f31;color:#fff;border-color:#254f31}.ap-bday-list{display:grid;gap:9px}.ap-bday-person{display:grid;grid-template-columns:52px minmax(0,1fr) auto;gap:10px;align-items:center;background:#fff;border:1px solid #e0e7e1;border-radius:17px;padding:11px}.ap-bday-date{font-size:11px;font-weight:900;color:#9a7420;background:#fff4cf;border-radius:12px;padding:7px;text-align:center}.ap-bday-person b{font-size:13px;display:block}.ap-bday-person small{display:block;color:#758078;margin-top:2px}.ap-bday-wa{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;text-decoration:none;background:#e6f3e8;color:#1e6131;border:1px solid #cce3d0;font-weight:900}.ap-bday-empty{padding:26px 12px;text-align:center;color:#758078}.ap-bday-count{font-size:11px;color:#7a827c;margin-bottom:10px}
@media(min-width:760px){.ap-bday-sheet{max-width:620px;left:50%;right:auto;transform:translateX(-50%);border-radius:28px;bottom:5vh}}
`;document.head.appendChild(s)}
function chipText(){const t=todayRows();if(t.length===1)return `Hoy · ${shortName(t[0].full_name)}`;if(t.length>1)return `Hoy cumplen ${t.length}`;const n=nextRows();if(!n.length)return 'Cumpleaños';const d=daysUntil(n[0].birthday_md);return d===1?`Mañana · ${shortName(n[0].full_name)}`:`Próximo ${dateLabel(n[0].birthday_md)} · ${shortName(n[0].full_name)}`}
function renderChip(){ensureStyles();let chip=document.getElementById('apBirthdayChip');const title=document.querySelector('.top .title,.title');if(!title)return;if(!chip){chip=document.createElement('button');chip.id='apBirthdayChip';chip.type='button';chip.onclick=()=>openModal('today');title.appendChild(chip)}chip.className='ap-bday-chip'+(todayRows().length?' today':'');chip.innerHTML=`<span class="cake">🎂</span><b>${esc(chipText())}</b>`}
function renderCard(){let card=document.getElementById('apBirthdayCard');const profile=document.querySelector('.online-profile');if(!profile){card?.remove();return}if(!card){card=document.createElement('div');card.id='apBirthdayCard';profile.insertAdjacentElement('afterend',card)}const t=todayRows(),n=nextRows();let title='Próximo cumpleaños',copy='Sin fechas disponibles';if(t.length===1){title='🎉 Cumpleaños de hoy';copy=t[0].full_name}else if(t.length>1){title=`🎉 ${t.length} cumpleaños hoy`;copy=t.map(x=>shortName(x.full_name)).join(' · ')}else if(n.length){title=`🎂 Próximo · ${dateLabel(n[0].birthday_md)}`;copy=n.length===1?n[0].full_name:`${n.length} compañeros`}
 card.className='ap-bday-card';card.innerHTML=`<div class="ico">🎂</div><div><b>${esc(title)}</b><small>${esc(copy)}</small></div><button class="open">Ver</button>`;card.querySelector('.open').onclick=()=>openModal(t.length?'today':'week')}
function renderAll(){renderChip();renderCard();if(document.getElementById('apBirthdayModal'))renderModal()}
function tabRows(){return modalTab==='today'?todayRows():modalTab==='week'?weekRows():monthRows()}
function renderModal(){const m=document.getElementById('apBirthdayModal');if(!m)return;const list=tabRows();m.innerHTML=`<div class="ap-bday-back" data-close></div><div class="ap-bday-sheet"><div class="ap-bday-head"><div><small>CUMPLEAÑOS · ${esc(courseCode||'')}</small><h2>🎂 Cumpleaños</h2></div><button class="ap-bday-close" data-close>×</button></div><div class="ap-bday-tabs"><button data-tab="today" class="${modalTab==='today'?'active':''}">Hoy (${todayRows().length})</button><button data-tab="week" class="${modalTab==='week'?'active':''}">Próximos 7 días (${weekRows().length})</button><button data-tab="month" class="${modalTab==='month'?'active':''}">Este mes (${monthRows().length})</button></div><div class="ap-bday-count">Se muestra únicamente día/mes. El año de nacimiento permanece privado.</div><div class="ap-bday-list">${list.length?list.map(r=>{const ph=digits(r.phone),wa=intl(ph);const d=daysUntil(r.birthday_md);const when=d===0?'Hoy':d===1?'Mañana':`En ${d} días`;return `<div class="ap-bday-person"><div class="ap-bday-date">${esc(dateLabel(r.birthday_md))}</div><div><b>${esc(r.grade||'')} ${esc(r.full_name)}</b><small>${esc(when)}</small></div>${ph.length>=7?`<a class="ap-bday-wa" href="https://wa.me/${wa}" target="_blank" rel="noopener" aria-label="Felicitar por WhatsApp">WA</a>`:'<span></span>'}</div>`}).join(''):'<div class="ap-bday-empty">No hay cumpleaños en este periodo.</div>'}</div></div>`;m.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);m.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{modalTab=x.dataset.tab;renderModal()})}
function openModal(tab='today'){modalTab=tab;let m=document.getElementById('apBirthdayModal');if(!m){m=document.createElement('div');m.id='apBirthdayModal';m.className='ap-bday-modal';document.body.appendChild(m)}renderModal()}
function closeModal(){document.getElementById('apBirthdayModal')?.remove()}
function boot(){ensureStyles();load(false);let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;const next=detectCourse();if(next!==courseCode){courseCode=next;load(true)}else renderAll()})}).observe(document.getElementById('app')||document.body,{childList:true,subtree:true})}
window.addEventListener('DOMContentLoaded',boot);window.addEventListener('online',()=>load(true));window.AgendaBirthdays={version:VERSION,open:openModal,refresh:()=>load(true)};
})();
