(()=>{
'use strict';
const VERSION='2.22.1';
const CACHE_PREFIX='agenda-birthdays-v2221';
let rows=[];
let courseCode=null;
let modalTab='today';
let loading=true;
let loadError='';
let lastCardSig='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const digits=s=>String(s||'').replace(/\D/g,'');
const intl=s=>{const d=digits(s);return d.startsWith('591')?d:(d.length===8?'591'+d:d)};
function session(){try{return typeof academicSession!=='undefined'&&academicSession?academicSession:JSON.parse(localStorage.getItem('agenda-academic-session')||'null')}catch{return null}}
function detectCourse(){const s=session();if(s?.course_code)return s.course_code;const selected=[...document.querySelectorAll('select')].find(x=>/capitanes|suboficiales|sargentos/i.test(x.selectedOptions?.[0]?.textContent||''));const txt=selected?.selectedOptions?.[0]?.textContent||'';const val=selected?.value||'';if(/^(capitanes|suboficiales|sargentos)-[a-f]-2026-2$/i.test(val))return val;if(/capitanes\s*b/i.test(txt))return'capitanes-b-2026-2';if(/capitanes\s*a/i.test(txt))return'capitanes-a-2026-2';return s?.selected_course_code||'capitanes-a-2026-2'}
function cacheKey(){const s=session();return`${CACHE_PREFIX}:${s?.user_id||'anon'}:${courseCode||'none'}`}
function todayLocal(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function occurrence(md,base=todayLocal()){const m=Number(md?.slice(0,2)),day=Number(md?.slice(3,5));if(!m||!day)return null;let y=base.getFullYear(),x=new Date(y,m-1,day);if(x<base)x=new Date(y+1,m-1,day);return x}
function daysUntil(md){const a=todayLocal(),b=occurrence(md,a);return b?Math.round((b-a)/86400000):999}
function dateLabel(md){const m=Number(md?.slice(0,2)),d=Number(md?.slice(3,5));const months=['ENE','FEB','MAR','ABR','MAY','JUN','JUL','AGO','SEP','OCT','NOV','DIC'];return`${String(d).padStart(2,'0')} ${months[m-1]||''}`}
function shortName(n=''){const p=String(n).trim().split(/\s+/);return p.length<=4?p.join(' '):p.slice(0,4).join(' ')}
function sorted(){return[...rows].sort((a,b)=>daysUntil(a.birthday_md)-daysUntil(b.birthday_md)||String(a.full_name).localeCompare(String(b.full_name),'es'))}
function todayRows(){return rows.filter(r=>daysUntil(r.birthday_md)===0)}
function weekRows(){return sorted().filter(r=>daysUntil(r.birthday_md)<=7)}
function monthRows(){const m=new Date().getMonth()+1;return rows.filter(r=>Number(r.birthday_md?.slice(0,2))===m).sort((a,b)=>Number(a.birthday_md.slice(3,5))-Number(b.birthday_md.slice(3,5))||String(a.full_name).localeCompare(String(b.full_name),'es'))}
function nextRows(){const s=sorted();if(!s.length)return[];const d=daysUntil(s[0].birthday_md);return s.filter(r=>daysUntil(r.birthday_md)===d)}
function saveCache(){try{const safe=rows.map(({person_id,roster_number,grade,full_name,course_code,birthday_md})=>({person_id,roster_number,grade,full_name,course_code,birthday_md}));sessionStorage.setItem(cacheKey(),JSON.stringify({courseCode,rows:safe,ts:Date.now()}))}catch{}}
function loadCache(){try{const c=JSON.parse(sessionStorage.getItem(cacheKey())||'null');if(c?.courseCode===courseCode&&Array.isArray(c.rows)&&c.rows.length){rows=c.rows;return true}}catch{}return false}
async function rpcBirthdays(){const s=session();if(!s?.session_token)throw new Error('Sesión académica requerida');if(typeof window.academicRPC!=='function')throw new Error('Modo online no disponible');const data=await window.academicRPC('academic_birthdays_v2',{p_token:s.session_token,p_course_code:courseCode});return Array.isArray(data)?data:[]}
async function load(force=false){courseCode=detectCourse();loadError='';const s=session();if(!s?.session_token){rows=[];loading=false;loadError='';renderAll();return rows}const cached=!force&&loadCache();loading=!cached;renderAll();if(!navigator.onLine){loading=false;if(!rows.length)loadError='Sin conexión y sin fechas guardadas';renderAll();return rows}try{const r=await rpcBirthdays();rows=r.filter(x=>/^\d{2}-\d{2}$/.test(String(x?.birthday_md||'')));saveCache();loading=false;loadError='';renderAll()}catch(e){console.warn('Cumpleaños: error de sincronización',e);loading=false;loadError=rows.length?'':'No se pudo sincronizar';renderAll()}return rows}
function ensureStyles(){if(document.getElementById('birthday2221Styles'))return;document.querySelectorAll('[id^="birthday221"]').forEach(x=>x.remove());const s=document.createElement('style');s.id='birthday2221Styles';s.textContent=`
.ap-bday-card{margin:9px 12px 13px;padding:7px 8px 7px 9px;border-radius:999px;border:1px solid rgba(166,139,57,.42);background:linear-gradient(135deg,rgba(255,252,238,.96),rgba(239,247,238,.98));display:grid;grid-template-columns:34px minmax(0,1fr) 34px;gap:9px;align-items:center;box-shadow:0 5px 15px rgba(25,55,34,.07);min-height:50px}.ap-bday-card .ico{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#fff1c0,#f8e5a5);font-size:18px;box-shadow:inset 0 0 0 1px rgba(174,138,38,.12)}.ap-bday-card .copy{min-width:0}.ap-bday-card .eyebrow{display:block;font-size:8px;line-height:1.1;font-weight:900;letter-spacing:.12em;color:#99741e;text-transform:uppercase;margin-bottom:2px}.ap-bday-card b{display:block;font-size:12px;line-height:1.2;color:#24422d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ap-bday-card small{display:block;font-size:10px;line-height:1.15;color:#788079;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ap-bday-card .open{width:34px;height:34px;border:0;border-radius:50%;background:#214f32;color:#fff;font-size:22px;line-height:1;display:grid;place-items:center;padding:0;box-shadow:0 4px 10px rgba(30,78,48,.18)}
.ap-bday-modal{position:fixed;inset:0;z-index:90}.ap-bday-back{position:absolute;inset:0;background:rgba(0,0,0,.42)}.ap-bday-sheet{position:absolute;left:0;right:0;bottom:0;max-height:88dvh;overflow:auto;background:#f8faf7;border-radius:28px 28px 0 0;padding:18px 16px calc(20px + env(safe-area-inset-bottom));box-shadow:0 -18px 50px rgba(0,0,0,.25)}.ap-bday-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.ap-bday-head h2{margin:0;font-size:24px}.ap-bday-close{border:0;width:38px;height:38px;border-radius:13px;background:#e8eee9;font-size:24px;color:#23442e}.ap-bday-tabs{display:flex;gap:7px;overflow:auto;margin:15px 0 12px}.ap-bday-tabs button{border:1px solid #d7e0d8;background:#fff;border-radius:999px;padding:8px 11px;font-weight:800;color:#546258;white-space:nowrap}.ap-bday-tabs button.active{background:#254f31;color:#fff;border-color:#254f31}.ap-bday-list{display:grid;gap:9px}.ap-bday-person{display:grid;grid-template-columns:52px minmax(0,1fr) auto;gap:10px;align-items:center;background:#fff;border:1px solid #e0e7e1;border-radius:17px;padding:11px}.ap-bday-date{font-size:11px;font-weight:900;color:#9a7420;background:#fff4cf;border-radius:12px;padding:7px;text-align:center}.ap-bday-person b{font-size:13px;display:block}.ap-bday-person small{display:block;color:#758078;margin-top:2px}.ap-bday-wa{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;text-decoration:none;background:#e6f3e8;color:#1e6131;border:1px solid #cce3d0;font-weight:900}.ap-bday-empty{padding:26px 12px;text-align:center;color:#758078}.ap-bday-count{font-size:11px;color:#7a827c;margin-bottom:10px}.ap-bday-retry{display:inline-flex;margin-top:10px;border:0;border-radius:999px;background:#254f31;color:#fff;padding:8px 13px;font-weight:800}@media(min-width:760px){.ap-bday-sheet{max-width:620px;left:50%;right:auto;transform:translateX(-50%);border-radius:28px;bottom:5vh}}
`;document.head.appendChild(s)}
function cardData(){const t=todayRows(),n=nextRows();if(loading&&!rows.length)return{eyebrow:'Cumpleaños',title:'Sincronizando fechas…',sub:'',tab:'week'};if(loadError&&!rows.length)return{eyebrow:'Cumpleaños',title:'No se pudo sincronizar',sub:'Toca para reintentar',tab:'week'};if(t.length===1)return{eyebrow:'Cumpleaños de hoy',title:`🎉 ${shortName(t[0].full_name)}`,sub:'¡Felicidades!',tab:'today'};if(t.length>1)return{eyebrow:'Cumpleaños de hoy',title:`🎉 Hoy cumplen ${t.length} compañeros`,sub:t.map(x=>shortName(x.full_name)).join(' · '),tab:'today'};if(n.length){const d=daysUntil(n[0].birthday_md),when=d===1?'Mañana':`Próximo · ${dateLabel(n[0].birthday_md)}`;return{eyebrow:'Cumpleaños',title:n.length===1?`${when} · ${shortName(n[0].full_name)}`:`${when} · ${n.length} compañeros`,sub:n.length===1?'Toca para ver próximos':'Toca para ver la lista',tab:'week'}}return{eyebrow:'Cumpleaños',title:'Sin fechas registradas',sub:'',tab:'month'}}
function renderCard(){ensureStyles();document.getElementById('apBirthdayChip')?.remove();let card=document.getElementById('apBirthdayCard');const profile=document.querySelector('.online-profile');if(!profile||!session()?.session_token){card?.remove();return}if(!card){card=document.createElement('button');card.id='apBirthdayCard';card.type='button';profile.insertAdjacentElement('afterend',card)}const d=cardData(),sig=JSON.stringify(d);if(sig===lastCardSig&&card.isConnected)return;lastCardSig=sig;card.className='ap-bday-card';card.innerHTML=`<span class="ico">🎂</span><span class="copy"><span class="eyebrow">${esc(d.eyebrow)}</span><b>${esc(d.title)}</b>${d.sub?`<small>${esc(d.sub)}</small>`:''}</span><span class="open" aria-hidden="true">›</span>`;card.onclick=()=>{if(loadError&&!rows.length)load(true);openModal(d.tab)}}
function tabRows(){return modalTab==='today'?todayRows():modalTab==='week'?weekRows():monthRows()}
function renderModal(){const m=document.getElementById('apBirthdayModal');if(!m)return;const list=tabRows();let body;if(loading&&!rows.length)body='<div class="ap-bday-empty">Sincronizando cumpleaños…</div>';else if(loadError&&!rows.length)body=`<div class="ap-bday-empty">No se pudo sincronizar.<br><button class="ap-bday-retry" data-retry>Reintentar</button></div>`;else body=list.length?list.map(r=>{const ph=digits(r.phone),wa=intl(ph),d=daysUntil(r.birthday_md),when=d===0?'Hoy':d===1?'Mañana':`En ${d} días`;return`<div class="ap-bday-person"><div class="ap-bday-date">${esc(dateLabel(r.birthday_md))}</div><div><b>${esc(r.grade||'')} ${esc(r.full_name)}</b><small>${esc(when)}</small></div>${ph.length>=7?`<a class="ap-bday-wa" href="https://wa.me/${wa}" target="_blank" rel="noopener">WA</a>`:'<span></span>'}</div>`}).join(''):'<div class="ap-bday-empty">No hay cumpleaños en este periodo.</div>';m.innerHTML=`<div class="ap-bday-back" data-close></div><div class="ap-bday-sheet"><div class="ap-bday-head"><div><small>CUMPLEAÑOS · ${esc(courseCode||'')}</small><h2>🎂 Cumpleaños</h2></div><button class="ap-bday-close" data-close>×</button></div><div class="ap-bday-tabs"><button data-tab="today" class="${modalTab==='today'?'active':''}">Hoy (${todayRows().length})</button><button data-tab="week" class="${modalTab==='week'?'active':''}">Próximos 7 días (${weekRows().length})</button><button data-tab="month" class="${modalTab==='month'?'active':''}">Este mes (${monthRows().length})</button></div><div class="ap-bday-count">Se muestra únicamente día/mes. El año de nacimiento permanece privado.</div><div class="ap-bday-list">${body}</div></div>`;m.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);m.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{modalTab=x.dataset.tab;renderModal()});m.querySelector('[data-retry]')?.addEventListener('click',()=>load(true))}
function renderAll(){renderCard();if(document.getElementById('apBirthdayModal'))renderModal()}
function openModal(tab='today'){if(!session()?.session_token)return;modalTab=tab;let m=document.getElementById('apBirthdayModal');if(!m){m=document.createElement('div');m.id='apBirthdayModal';m.className='ap-bday-modal';document.body.appendChild(m)}renderModal()}
function closeModal(){document.getElementById('apBirthdayModal')?.remove()}
function boot(){ensureStyles();courseCode=detectCourse();load(false);const target=document.getElementById('app')||document.body;let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;const next=detectCourse();if(next!==courseCode){courseCode=next;rows=[];lastCardSig='';load(true)}else renderCard()})}).observe(target,{childList:true,subtree:true})}
window.addEventListener('DOMContentLoaded',boot);window.addEventListener('online',()=>load(true));window.AgendaBirthdays={version:VERSION,open:openModal,refresh:()=>load(true)};
})();