/* Agenda Policial Online v2.6.0 - módulo académico opcional */
const ONLINE_CFG={url:'',anonKey:'',bucket:'academic-files'};
const ACADEMIC_TYPES={examenes:'Exámenes',formaciones:'Formaciones',tareas:'Tareas',resumenes:'Resúmenes'};
let academicSession=JSON.parse(localStorage.getItem('agenda-academic-session')||'null');
let academicTab='formaciones';
function onlineConfigured(){return Boolean(ONLINE_CFG.url&&ONLINE_CFG.anonKey)}
function academicHeaders(){return {'apikey':ONLINE_CFG.anonKey,'Authorization':'Bearer '+ONLINE_CFG.anonKey,'Content-Type':'application/json'}}
async function academicRPC(fn,body={}){const r=await fetch(`${ONLINE_CFG.url}/rest/v1/rpc/${fn}`,{method:'POST',headers:academicHeaders(),body:JSON.stringify(body)}); if(!r.ok)throw new Error(await r.text()); return await r.json()}
async function academicLogin(){const ci=$('#academicCi')?.value.trim(), phone=$('#academicPhone')?.value.trim(); if(!ci||!phone)return toast('Ingrese carnet y número celular'); try{let u;if(onlineConfigured()){u=await academicRPC('academic_login',{p_ci:ci,p_phone:phone}); if(Array.isArray(u))u=u[0]}else{u=demoLogin(ci,phone)} if(!u||!u.session_token)return toast('Datos no registrados o acceso inactivo'); academicSession=u; localStorage.setItem('agenda-academic-session',JSON.stringify(u)); render(); toast('Acceso académico habilitado')}catch(e){console.error(e);toast('No se pudo conectar al área académica')}}
function demoLogin(ci,phone){if(ci==='0000'&&phone==='0000')return {session_token:'demo-admin',full_name:'Administrador de demostración',role:'administrador_general',user_id:'demo'}; return null}
function academicLogout(){academicSession=null;localStorage.removeItem('agenda-academic-session');render();toast('Sesión académica cerrada')}
function renderOnline(){if(!academicSession)return `<section><div class="online-hero"><span class="eyebrow">Módulo opcional</span><h2>Área académica online</h2><p>El acceso online es exclusivo para integrantes registrados. La biblioteca y todas las funciones offline continúan disponibles para los demás usuarios.</p></div><div class="card academic-login"><h3>Identificación académica</h3><label>Número de carnet<input id="academicCi" inputmode="numeric" autocomplete="username" placeholder="Ej.: 6458217"></label><label>Número de celular<input id="academicPhone" inputmode="tel" autocomplete="current-password" placeholder="Ej.: 72123456" type="password"></label><button class="btn" onclick="academicLogin()">Ingresar al contenido online</button>${!onlineConfigured()?'<p class="subtle">Modo de preparación activo. Para probar: carnet 0000 y celular 0000.</p>':''}</div></section>`;
 const canPublish=['administrador_general','encargado_curso','administrador_academico','asistente_academico'].includes(academicSession.role);
 return `<section><div class="row between wrap"><div><span class="eyebrow">Área académica</span><h2>${esc(academicSession.full_name||'Usuario')}</h2><p class="subtle">${academicRoleLabel(academicSession.role)}</p></div><button class="btn secondary" onclick="academicLogout()">Cerrar acceso online</button></div><div class="academic-tabs">${Object.entries(ACADEMIC_TYPES).map(([k,v])=>`<button class="${academicTab===k?'active':''}" onclick="setAcademicTab('${k}')">${v}</button>`).join('')}</div>${canPublish?`<div class="row between"><h3>${ACADEMIC_TYPES[academicTab]}</h3><button class="btn" onclick="openAcademicPostForm('${academicTab}')">Nueva publicación</button></div>`:`<h3>${ACADEMIC_TYPES[academicTab]}</h3>`}<div id="academicPosts"><div class="card small"><p>Cargando contenido…</p></div></div></section>`}
function academicRoleLabel(r){return ({administrador_general:'Administrador general',encargado_curso:'Encargado de curso',administrador_academico:'Administrador académico',asistente_academico:'Asistente académico',lector:'Lector'})[r]||'Lector'}
async function setAcademicTab(t){academicTab=t;render();setTimeout(loadAcademicPosts,0)}
async function loadAcademicPosts(){const box=$('#academicPosts');if(!box||!academicSession)return;try{let posts;if(onlineConfigured())posts=await academicRPC('academic_get_posts',{p_token:academicSession.session_token,p_type:academicTab});else posts=JSON.parse(localStorage.getItem('agenda-demo-posts')||'[]').filter(p=>p.post_type===academicTab); box.innerHTML=posts.length?posts.map(academicPostCard).join(''):'<div class="card small"><p>No existen publicaciones en esta sección.</p></div>'}catch(e){box.innerHTML='<div class="card small warn-card"><p>No fue posible sincronizar el contenido.</p></div>'}}
function academicPostCard(p){const f=p.fields||{};let meta='';if(p.post_type==='formaciones')meta=`<div class="formation-meta"><span>📅 ${esc(f.date||'Sin fecha')}</span><span>📍 ${esc(f.place||'Sin lugar')}</span><span>🕘 Control: ${esc(f.control_time||'-')}</span><span>🕙 Parte: ${esc(f.report_time||'-')}</span></div>`; if(p.post_type==='resumenes')meta=`<p><b>Materia:</b> ${esc(f.subject||'')} · <b>Tema:</b> ${esc(f.topic||'')}</p>`;return `<article class="card academic-post"><div class="row between"><span class="tag">${esc(ACADEMIC_TYPES[p.post_type]||p.post_type)}</span><small>${esc(p.author_name||'')}</small></div><h3>${esc(p.title||'Sin título')}</h3>${meta}<p>${esc(p.body||'')}</p>${f.uniform?`<p><b>Uniforme:</b> ${esc(f.uniform)}</p>`:''}${f.observations?`<p><b>Observaciones:</b> ${esc(f.observations)}</p>`:''}${p.file_url?`<a class="btn secondary link-btn" href="${esc(p.file_url)}" target="_blank" rel="noopener">Abrir archivo adjunto</a>`:''}<small class="subtle">${new Date(p.created_at||Date.now()).toLocaleString('es-BO')}</small></article>`}
function openAcademicPostForm(type){const common=`<label>Título<input name="title" required></label><label>Comunicado / texto<textarea name="body" rows="6"></textarea></label>`;let fields='';if(type==='formaciones')fields=`<label>Tipo<select name="formation_type"><option>Formación general</option><option>Servicio extraordinario</option></select></label><label>Fecha<input name="date" type="date" required></label><label>Lugar<input name="place" required></label><div class="two-col"><label>Hora de control<input name="control_time" type="time"></label><label>Hora del parte<input name="report_time" type="time"></label></div><label>Uniforme<input name="uniform"></label><label>Observaciones<textarea name="observations" rows="3"></textarea></label>`;if(type==='resumenes')fields=`<label>Materia<input name="subject" required></label><label>Tema<input name="topic" required></label>`;if(type==='tareas')fields=`<label>Materia<input name="subject"></label><label>Fecha límite<input name="due_date" type="date"></label>`;if(type==='examenes')fields=`<label>Materia<input name="subject"></label><label>Fecha<input name="date" type="date"></label><label>Hora<input name="time" type="time"></label><label>Lugar<input name="place"></label>`;showModal(`<button class="icon-btn close" onclick="closeModal()">×</button><h2>Nueva publicación</h2><form id="academicPostForm" class="form">${common}${fields}<label>Archivo opcional (Word, PDF o imagen)<input id="academicFile" type="file" accept=".doc,.docx,.pdf,image/*"></label><div class="form-actions"><button class="btn" type="submit">Publicar</button><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button></div></form>`);$('#academicPostForm').onsubmit=saveAcademicPost}
async function uploadAcademicFile(file){if(!file)return null;if(!onlineConfigured()){return 'data:'+file.type+';base64,'+await file.arrayBuffer().then(b=>btoa(String.fromCharCode(...new Uint8Array(b))))}const safe=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const r=await fetch(`${ONLINE_CFG.url}/storage/v1/object/${ONLINE_CFG.bucket}/${safe}`,{method:'POST',headers:{'apikey':ONLINE_CFG.anonKey,'Authorization':'Bearer '+ONLINE_CFG.anonKey,'x-upsert':'false','Content-Type':file.type||'application/octet-stream'},body:file});if(!r.ok)throw new Error(await r.text());return `${ONLINE_CFG.url}/storage/v1/object/public/${ONLINE_CFG.bucket}/${safe}`}
async function saveAcademicPost(e){e.preventDefault();const fd=new FormData(e.target), obj=Object.fromEntries(fd.entries());const title=obj.title,body=obj.body;delete obj.title;delete obj.body;try{const file=$('#academicFile')?.files?.[0];const file_url=await uploadAcademicFile(file);if(onlineConfigured())await academicRPC('academic_create_post',{p_token:academicSession.session_token,p_type:academicTab,p_title:title,p_body:body,p_fields:obj,p_file_url:file_url});else{const a=JSON.parse(localStorage.getItem('agenda-demo-posts')||'[]');a.unshift({id:uid(),post_type:academicTab,title,body,fields:obj,file_url,author_name:academicSession.full_name,created_at:new Date().toISOString()});localStorage.setItem('agenda-demo-posts',JSON.stringify(a))}closeModal();loadAcademicPosts();toast('Publicación guardada')}catch(err){console.error(err);toast('No se pudo guardar la publicación')}}
const _renderOriginal=render;render=function(){_renderOriginal();if(state.activated&&state.mode&&state.view==='online')setTimeout(loadAcademicPosts,0)};
