(()=>{
'use strict';
const VERSION='2.21.14',DATA_VERSION='2026-09-03';
const FILES={alfa:{capitanes:'./data/grupos/alfa-capitanes.json',suboficiales_segundos:'./data/grupos/alfa-suboficiales-segundos.json',sargentos_segundos:'./data/grupos/alfa-sargentos-segundos.json'},bravo:{capitanes:'./data/grupos/bravo-capitanes.json',suboficiales_segundos:'./data/grupos/bravo-suboficiales-segundos.json',sargentos_segundos:'./data/grupos/bravo-sargentos-segundos.json'}};
const LABELS={capitanes:'CAPITANES',suboficiales_segundos:'SUBOFICIALES SEGUNDOS',sargentos_segundos:'SARGENTOS SEGUNDOS'};
const state={data:{},contacts:{},matches:{},group:localStorage.getItem('agenda-service-group')||'bravo',query:'',section:'all',department:'all',mode:localStorage.getItem('agenda-service-view')||'compact',loading:false,error:'',updatedAt:null,selected:new Set()};
let switchToken=0;
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ ]/g,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digits=s=>String(s||'').replace(/\D/g,'');
const intl=s=>{const d=digits(s);return d.startsWith('591')?d:(d.length===8?'591'+d:d)};
function ensureStyles(){if(document.getElementById('sgContactsV22114'))return;const s=document.createElement('style');s.id='sgContactsV22114';s.textContent=`.sg-toolbar{grid-template-columns:repeat(2,minmax(0,1fr))!important}.sg-row{grid-template-columns:26px 42px 70px minmax(0,1fr) 70px!important}.sg-contact-actions{display:flex;justify-content:flex-end;gap:5px}.sg-contact-actions a,.sg-contact-missing{width:30px;height:30px;border-radius:10px;display:grid;place-items:center;text-decoration:none;font-weight:900;border:1px solid #cbd8d0;background:#f5f8f6;color:#244d35;font-size:14px}.sg-contact-actions .wa{background:#e2f4e5;color:#17622e;border-color:#c8e5cd}.sg-contact-actions .call{background:#edf1ee;color:#284d38}.sg-contact-missing{opacity:.32}.sg-phone{display:block;font-size:9px;color:#718078;margin-top:3px}@media(max-width:700px){.sg-row{grid-template-columns:24px 30px 54px minmax(0,1fr) 66px!important}.sg-contact-actions a,.sg-contact-missing{width:29px;height:29px}}@media(max-width:430px){.sg-row{grid-template-columns:22px 28px 48px minmax(0,1fr) 62px!important;gap:5px}.sg-contact-actions{gap:3px}.sg-contact-actions a,.sg-contact-missing{width:28px;height:28px}}`;document.head.appendChild(s)}
function dbOpen(){return new Promise((res,rej)=>{const q=indexedDB.open('agenda-policial-db',1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('kv'))q.result.createObjectStore('kv')}})}
async function dbGet(k){try{const db=await dbOpen();return await new Promise(r=>{const q=db.transaction('kv','readonly').objectStore('kv').get(k);q.onsuccess=()=>r(q.result);q.onerror=()=>r(null)})}catch{return null}}
async function dbSet(k,v){try{const db=await dbOpen();await new Promise((r,j)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(v,k);tx.oncomplete=r;tx.onerror=()=>j(tx.error)})}catch{}}
async function loadContacts(force=false){
  const cached=await dbGet('serviceGroups:contacts-v22114');
  if(cached?.data&&!Object.keys(state.contacts).length)state.contacts=cached.data;
  if(!force&&cached?.data&&(!navigator.onLine||typeof window.academicRPC!=='function'))return state.contacts;
  if(!navigator.onLine||typeof window.academicRPC!=='function')return state.contacts;
  try{
    const rows=await window.academicRPC('academic_personnel_directory',{p_course_code:null,p_department:null,p_search:null})||[];
    const map={};
    rows.forEach(p=>{const k=norm(p.full_name);if(!k)return;map[k]={phone:digits(p.phone),department:String(p.department||'').trim(),unit:String(p.source_unit||'').trim(),course:String(p.course_code||'')}});
    if(Object.keys(map).length){state.contacts=map;state.matches={};await dbSet('serviceGroups:contacts-v22114',{version:VERSION,data:map,updatedAt:Date.now()})}
  }catch(e){console.warn('Contactos de servicio: usando caché offline',e)}
  return state.contacts;
}
function tokenScore(a,b){const A=[...new Set(norm(a).split(' ').filter(x=>x.length>1))],B=[...new Set(norm(b).split(' ').filter(x=>x.length>1))];if(!A.length||!B.length)return 0;const common=A.filter(x=>B.includes(x)).length;return common/Math.max(A.length,B.length)}
function meta(x){const key=norm(x.nombre);if(state.matches[key]!==undefined)return state.matches[key];if(state.contacts[key])return state.matches[key]=state.contacts[key];let best=null,score=0;for(const [k,v] of Object.entries(state.contacts)){const s=tokenScore(key,k);if(s>score){score=s;best=v}}return state.matches[key]=(score>=.74?best:null)}
async function fetchGroup(id){return Object.fromEntries(await Promise.all(Object.entries(FILES[id]).map(async([section,path])=>{const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw 0;const j=await r.json();return[section,j.integrantes||[]]})))}
async function loadGroup(id,force=false){const token=++switchToken;if(!force&&state.data[id])return state.data[id];const c=await dbGet('serviceGroups:'+id);if(c?.data&&!state.data[id])state.data[id]=c.data;if(!force&&state.data[id]){renderModal();return state.data[id]}try{state.loading=true;renderModal();const d=await fetchGroup(id);state.data[id]=d;state.updatedAt=Date.now();await dbSet('serviceGroups:'+id,{version:VERSION,data:d,updatedAt:state.updatedAt})}catch{if(!state.data[id])state.error='No se pudo cargar la nómina.'}finally{if(token===switchToken){state.loading=false;renderModal()}}return state.data[id]}
function pkey(section,x){return`${state.group}|${section}|${norm(x.nombre)}`}
function row(x,section){const key=pkey(section,x),m=meta(x),dep=m?.department||'',ph=digits(m?.phone),wa=intl(ph);const actions=ph.length>=7?`<span class="sg-contact-actions"><a class="call" href="tel:${ph}" data-sg-contact title="Llamar" aria-label="Llamar a ${esc(x.nombre)}">☎</a><a class="wa" href="https://wa.me/${wa}" target="_blank" rel="noopener" data-sg-contact title="WhatsApp" aria-label="WhatsApp a ${esc(x.nombre)}">◉</a></span>`:`<span class="sg-contact-actions"><span class="sg-contact-missing" title="Sin teléfono registrado">—</span></span>`;return`<div class="sg-row ${state.mode==='detail'?'detail':''}" data-sg-person="${esc(key)}" data-sg-search="${esc(norm(`${x.numero_fuente} ${x.grado} ${x.nombre} ${dep} ${m?.unit||''}`))}" data-sg-section="${section}" data-sg-department="${esc(dep)}"><label class="sg-select"><input type="checkbox" data-sg-select="${esc(key)}" ${state.selected.has(key)?'checked':''}></label><span class="sg-num">${esc(x.numero_fuente)}</span><span class="sg-grade">${esc(x.grado)}</span><span class="sg-name">${esc(x.nombre)}${dep?`<small class="sg-origin">Comisionado desde: ${esc(dep)}</small>`:''}${state.mode==='detail'&&ph?`<small class="sg-phone">Cel. ${esc(ph)}</small>`:''}</span>${actions}</div>`}
function sections(data){return Object.entries(LABELS).map(([k,l])=>`<section class="sg-section" data-sg-section-box="${k}"><h3>${l} <span data-sg-section-count>${(data[k]||[]).length}</span></h3><div class="sg-list">${(data[k]||[]).map(x=>row(x,k)).join('')}</div></section>`).join('')}
function modal(){return document.getElementById('serviceGroupsModal')}
function renderModal(){ensureStyles();const m=modal();if(!m)return;const data=state.data[state.group]||{},all=Object.values(data).reduce((a,x)=>a+x.length,0),deps=[...new Set(Object.values(data).flat().map(x=>meta(x)?.department).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')),available=Object.values(data).flat().filter(x=>digits(meta(x)?.phone).length>=7).length;m.innerHTML=`<div class="sg-backdrop" data-sg-close></div><div class="sg-panel"><header class="sg-head"><div><div class="sg-kicker">GRUPOS DE SERVICIO · OFFLINE · v${VERSION}</div><h2>Mi grupo de servicio</h2><small>Base ${DATA_VERSION} · contactos sincronizados</small></div><button class="sg-close" data-sg-close>×</button></header><div class="sg-tabs"><button data-sg-group="alfa" class="${state.group==='alfa'?'active':''}">Grupo Alfa</button><button data-sg-group="bravo" class="${state.group==='bravo'?'active':''}">Grupo Bravo</button></div><div class="sg-toolbar"><button data-sg-mode>${state.mode==='compact'?'Vista detallada':'Vista compacta'}</button><button data-sg-refresh>↻ Actualizar contactos</button></div><div class="sg-tools"><input id="sgSearch" value="${esc(state.query)}" placeholder="Buscar apellido, nombre, número o departamento…" autocomplete="off" spellcheck="false"><select id="sgSection"><option value="all">Toda la nómina</option>${Object.entries(LABELS).map(([k,v])=>`<option value="${k}" ${state.section===k?'selected':''}>${v}</option>`).join('')}</select>${deps.length?`<select id="sgDepartment"><option value="all">Todos los departamentos</option>${deps.map(d=>`<option ${state.department===d?'selected':''}>${esc(d)}</option>`).join('')}</select>`:''}</div>${state.loading?'<div class="sg-status">Actualizando nómina…</div>':''}${state.error?`<div class="sg-error">${esc(state.error)}</div>`:''}<div class="sg-result-count"><span>Mostrando <b id="sgShown">${all}</b> de ${all}</span><span>☎/WA disponibles: ${available}</span></div><div class="sg-content">${sections(data)}</div></div>`;bindModal();applyFilter()}
function applyFilter(){const m=modal();if(!m)return;const q=norm(state.query);let shown=0;const counts={};m.querySelectorAll('[data-sg-person]').forEach(el=>{const ok=(!q||el.dataset.sgSearch.includes(q))&&(state.section==='all'||el.dataset.sgSection===state.section)&&(state.department==='all'||el.dataset.sgDepartment===state.department);el.hidden=!ok;if(ok){shown++;counts[el.dataset.sgSection]=(counts[el.dataset.sgSection]||0)+1}});m.querySelectorAll('[data-sg-section-box]').forEach(box=>{const c=counts[box.dataset.sgSectionBox]||0;box.hidden=!c;const x=box.querySelector('[data-sg-section-count]');if(x)x.textContent=c});const s=m.querySelector('#sgShown');if(s)s.textContent=shown}
function bindModal(){const m=modal();if(!m)return;m.querySelectorAll('[data-sg-close]').forEach(x=>x.onclick=close);m.querySelectorAll('[data-sg-contact]').forEach(x=>x.onclick=e=>e.stopPropagation());m.querySelectorAll('[data-sg-group]').forEach(x=>x.onclick=()=>{if(x.dataset.sgGroup===state.group)return;state.group=x.dataset.sgGroup;state.query='';state.department='all';localStorage.setItem('agenda-service-group',state.group);state.data[state.group]?renderModal():loadGroup(state.group)});m.querySelector('[data-sg-mode]')?.addEventListener('click',()=>{state.mode=state.mode==='compact'?'detail':'compact';localStorage.setItem('agenda-service-view',state.mode);renderModal()});m.querySelector('[data-sg-refresh]')?.addEventListener('click',async()=>{await Promise.allSettled([loadContacts(true),loadGroup(state.group,true)]);renderModal()});const s=m.querySelector('#sgSearch');if(s)s.oninput=()=>{state.query=s.value;applyFilter()};const sec=m.querySelector('#sgSection');if(sec)sec.onchange=()=>{state.section=sec.value;applyFilter()};const dep=m.querySelector('#sgDepartment');if(dep)dep.onchange=()=>{state.department=dep.value;applyFilter()};m.querySelectorAll('[data-sg-select]').forEach(c=>c.onchange=()=>c.checked?state.selected.add(c.dataset.sgSelect):state.selected.delete(c.dataset.sgSelect))}
async function open(){if(modal())return;ensureStyles();const el=document.createElement('div');el.id='serviceGroupsModal';el.className='sg-modal';(document.getElementById('modalRoot')||document.body).appendChild(el);const c=await dbGet('serviceGroups:'+state.group);if(c?.data)state.data[state.group]=c.data;await loadContacts(false);renderModal();if(!state.data[state.group])await loadGroup(state.group);else loadGroup(state.group,true).catch(()=>{});loadContacts(true).then(()=>{if(modal())renderModal()})}
function close(){modal()?.remove()}
function integratedTile(){if(document.getElementById('serviceGroupsTile'))return true;const ref=[...document.querySelectorAll('button,.card,.tile,.menu-card,.quick-card,[data-view]')].find(x=>/biblioteca|horario|office/i.test(x.textContent||''));if(!ref?.parentElement)return false;const b=document.createElement('button');b.id='serviceGroupsTile';b.className=`${ref.className||''} sg-integrated`;b.type='button';b.innerHTML='<span>👥</span><span><b>Mi grupo de servicio</b><small>Alfa · Bravo · contactos offline</small></span>';b.onclick=open;ref.parentElement.appendChild(b);return true}
function ensureButton(){if(integratedTile()){document.getElementById('serviceGroupsQuick')?.remove();return}if(document.getElementById('serviceGroupsQuick'))return;const b=document.createElement('button');b.id='serviceGroupsQuick';b.className='sg-quick';b.innerHTML='<span class="sg-quick-icon">👥</span><span><b>Mi grupo de servicio</b><small>Alfa · Bravo · contactos</small></span>';b.onclick=open;document.body.appendChild(b)}
async function warm(){ensureStyles();await loadContacts(false);for(const id of['alfa','bravo']){const c=await dbGet('serviceGroups:'+id);if(c?.data)state.data[id]=c.data}if(navigator.onLine){loadContacts(true).catch(()=>{});Promise.allSettled(['alfa','bravo'].map(id=>fetchGroup(id).then(d=>{state.data[id]=d;return dbSet('serviceGroups:'+id,{version:VERSION,data:d,updatedAt:Date.now()})}))}}
window.addEventListener('online',()=>loadContacts(true).catch(()=>{}));window.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.addEventListener('DOMContentLoaded',()=>{ensureButton();warm();new MutationObserver(ensureButton).observe(document.getElementById('app')||document.body,{childList:true,subtree:true})});window.AgendaServiceGroups={open,version:VERSION,refresh:async()=>{await loadContacts(true);return loadGroup(state.group,true)}};
})();