-- Agenda Policial Online v2.6.0
create extension if not exists pgcrypto;
create table if not exists academic_users(id uuid primary key default gen_random_uuid(),full_name text not null,ci text unique not null,phone text not null,role text not null check(role in ('administrador_general','encargado_curso','administrador_academico','asistente_academico','lector')),active boolean not null default true,created_at timestamptz default now());
create table if not exists academic_sessions(token uuid primary key default gen_random_uuid(),user_id uuid references academic_users(id) on delete cascade,expires_at timestamptz default now()+interval '180 days',created_at timestamptz default now());
create table if not exists academic_posts(id uuid primary key default gen_random_uuid(),post_type text not null check(post_type in ('examenes','formaciones','tareas','resumenes')),title text not null,body text,fields jsonb not null default '{}'::jsonb,file_url text,author_id uuid references academic_users(id),created_at timestamptz default now(),updated_at timestamptz default now(),archived boolean default false);
alter table academic_users enable row level security; alter table academic_sessions enable row level security; alter table academic_posts enable row level security;
create or replace function academic_login(p_ci text,p_phone text) returns table(session_token uuid,user_id uuid,full_name text,role text) language plpgsql security definer set search_path=public as $$declare u academic_users; t uuid;begin select * into u from academic_users where ci=p_ci and phone=p_phone and active=true limit 1;if u.id is null then return;end if;insert into academic_sessions(user_id) values(u.id) returning token into t;return query select t,u.id,u.full_name,u.role;end$$;
create or replace function academic_get_posts(p_token uuid,p_type text) returns table(id uuid,post_type text,title text,body text,fields jsonb,file_url text,author_name text,created_at timestamptz) language sql security definer set search_path=public as $$select p.id,p.post_type,p.title,p.body,p.fields,p.file_url,u.full_name,p.created_at from academic_posts p join academic_users u on u.id=p.author_id where p.archived=false and p.post_type=p_type and exists(select 1 from academic_sessions s where s.token=p_token and s.expires_at>now()) order by p.created_at desc$$;
create or replace function academic_create_post(p_token uuid,p_type text,p_title text,p_body text,p_fields jsonb,p_file_url text default null) returns uuid language plpgsql security definer set search_path=public as $$declare u academic_users;newid uuid;begin select au.* into u from academic_sessions s join academic_users au on au.id=s.user_id where s.token=p_token and s.expires_at>now() and au.active=true;if u.id is null or u.role='lector' then raise exception 'No autorizado';end if;insert into academic_posts(post_type,title,body,fields,file_url,author_id) values(p_type,p_title,p_body,coalesce(p_fields,'{}'::jsonb),p_file_url,u.id) returning id into newid;return newid;end$$;
grant execute on function academic_login(text,text) to anon,authenticated;grant execute on function academic_get_posts(uuid,text) to anon,authenticated;grant execute on function academic_create_post(uuid,text,text,text,jsonb,text) to anon,authenticated;
-- Storage: crear bucket público academic-files y permitir INSERT/SELECT a anon; no habilitar DELETE.
